### ISSUE TITLE
yarn提交报错

### ISSUE THREAD

**Issue by LoveXiaoQuan** [DTStack/flinkx#102]
Caused by: org.apache.flink.runtime.client.JobExecutionException: Could not set up JobManager
	at org.apache.flink.runtime.jobmaster.JobManagerRunner.<init>(JobManagerRunner.java:176)
	at org.apache.flink.runtime.dispatcher.Dispatcher$DefaultJobManagerRunnerFactory.createJobManagerRunner(Dispatcher.java:1058)
	at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$createJobManagerRunner$5(Dispatcher.java:308)
	at org.apache.flink.util.function.CheckedSupplier.lambda$unchecked$0(CheckedSupplier.java:34)
	... 7 more
Caused by: org.apache.flink.runtime.client.JobExecutionException: Cannot initialize task 'Source: mysqlreader': Deserializing the InputFormat (null) failed: Could not read the user code wrapper: com.dtstack.flinkx.rdb.inputformat.JdbcInputFormat
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:220)
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:100)
	at org.apache.flink.runtime.jobmaster.JobMaster.createExecutionGraph(JobMaster.java:1173)
	at org.apache.flink.runtime.jobmaster.JobMaster.createAndRestoreExecutionGraph(JobMaster.java:1153)
	at org.apache.flink.runtime.jobmaster.JobMaster.<init>(JobMaster.java:296)
	at org.apache.flink.runtime.jobmaster.JobManagerRunner.<init>(JobManagerRunner.java:157)
	... 10 more
Caused by: java.lang.Exception: Deserializing the InputFormat (null) failed: Could not read the user code wrapper: com.dtstack.flinkx.rdb.inputformat.JdbcInputFormat
	at org.apache.flink.runtime.jobgraph.InputFormatVertex.initializeOnMaster(InputFormatVertex.java:66)
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:216)
	... 15 more

**Comment by kanata163** [comment]
Cannot initialize task 'Source: mysqlreader': Deserializing the InputFormat (null) failed: Could not read the user code wrapper: com.dtstack.flinkx.rdb.inputformat.JdbcInputFormat
报错原因已经很清楚了，你自己本地debug调试一下。
还有请尽量使用1.5或者1.8的flinkx版本，其他版本已经不再维护。
