### ISSUE TITLE
flink on yarn报错

### ISSUE THREAD

**Issue by momisabuilder** [DTStack/flinkx#142]
错误信息：
2019-12-18 16:25:56,752 INFO  org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl  - Interrupted while waiting for queue
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl$CallbackHandlerThread.run(AMRMClientAsyncImpl.java:323)

但是，似乎不影响任务的正常执行，数据可以正常同步，flink webui也能看到任务

**Comment by kanata163** [comment]
https://issues.apache.org/jira/browse/YARN-6166
没用的INFO日志，没啥影响。
