### ISSUE TITLE
hdfs的kerberos验证的问题

### ISSUE THREAD

**Issue by hungrytortoise** [DTStack/flinkx#157]
按照配置文档配置了kerberos认证的相关信息，但是启动的时候报如下错误：
19:09:28.213 [Sink: hdfswriter (1/1)] ERROR org.apache.flink.streaming.api.functions.sink.DtOutputFormatSinkFunction - Cleanup on error failed.
java.io.IOException: Failed on local exception: java.io.IOException: java.lang.IllegalArgumentException: Kerberos principal name does NOT have the expected hostname part: mis; Host Details : local host is: "Lxx/127.0.0.1"; destination host is: "xxx":8020;

不知道是不是因为跨集群访问的原因；
flink集群：集群A（无kerberos认证）
hdfs集群：集群B（kerberos认证）
配置文件如下：
{
"job": {
"content": [{
"reader": {
"parameter": {
"groupId": "testgroupid002",
"topic": "2019allin_calbrk",
"blankIgnore": true,
"codec": "plain",
"consumerSettings": {
"bootstrap.servers": "xxx.22.64.xx:9092",
"zookeeper.connect": "xxx.22.64.xx:2181",
"auto.commit.interval.ms": "1000",
"auto.offset.reset": "latest"
}
},
"name": "kafka10reader"
},
"writer": {
"parameter": {
"path": "/tmp/xx/flinkx",
"fileName": "testfile",
"hadoopConfig": {
"dfs.ha.namenodes.ns1": "nn1,nn2",
"dfs.namenode.rpc-address.ns1.nn2": "hadoop03:8022",
"dfs.client.failover.proxy.provider.ns1": "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider",
"dfs.namenode.rpc-address.ns1.nn1": "hadoop04:8022",
"dfs.nameservices": "xxx",
"hadoop.security.authorization": "true",
"hadoop.security.authentication": "Kerberos",
"dfs.namenode.kerberos.principal": "mis",
"dfs.namenode.keytab.file": "/home/devuser/project/flinkx/jobs/conf/mis.keytab",
"java.security.krb5.conf": "/home/devuser/project/flinkx/jobs/conf/krb5.conf",
"useLocalFile": true

				},
				"column": [{
					"name": "timestamp",
					"index": 0,
					"type": "string"
				}],
				"defaultFS": "hdfs://xxx",
				"writeMode": "APPEND",
				"fieldDelimiter": ",",
				"fileType": "orc",
				"charsetName": "utf-8"
			},
			"name": "hdfswriter",
			"type": 6
		}
	}],
	"setting": {
		"errorLimit": {
			"record": 1
		},
		"speed": {
			"bytes": 1048576,
			"channel": 1
		}
	}
}
}

**Comment by lijiangbo** [comment]
麻烦把命令：klist -kt /home/devuser/project/flinkx/jobs/conf/mis.keytab  的结果发一下

**Comment by hungrytortoise** [comment]
Keytab name: FILE:/home/devuser/project/flinkx/jobs/conf/mis.keytab
KVNO Timestamp         Principal
---- ----------------- --------------------------------------------------------
  10 01/02/18 11:32:24 mis@LUFAX.STORAGE
  10 01/02/18 11:32:24 mis@LUFAX.STORAGE
  10 01/02/18 11:32:24 mis@xx.STORAGE
  10 01/02/18 11:32:24 mis@xx.STORAGE
  10 01/02/18 11:32:24 mis@xx.STORAGE
  10 01/02/18 11:32:24 mis@xx.STORAGE

**Comment by hungrytortoise** [comment]
@lijiangbo 
Keytab name: FILE:/home/devuser/project/flinkx/jobs/conf/mis.keytab
KVNO Timestamp         Principal
---- ----------------- --------------------------------------------------------
  10 01/02/18 11:32:24 mis@xxx.STORAGE
  10 01/02/18 11:32:24 mis@xxx.STORAGE
  10 01/02/18 11:32:24 mis@xxx.STORAGE
  10 01/02/18 11:32:24 mis@xxx.STORAGE
  10 01/02/18 11:32:24 mis@xxx.STORAGE
  10 01/02/18 11:32:24 mis@xxx.STORAGE

**Comment by lijiangbo** [comment]
这个参数 dfs.namenode.kerberos.principal 可以写  mis@xxx.STORAGE 试一下

**Comment by hungrytortoise** [comment]
Caused by: java.io.IOException: java.lang.IllegalArgumentException: Kerberos principal name does NOT have the expected hostname part: mis@xxx.STORAGE
	at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:677)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1556)
	at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:640)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:724)
	at org.apache.hadoop.ipc.Client$Connection.access$2800(Client.java:367)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1462)
	at org.apache.hadoop.ipc.Client.call(Client.java:1381)
	... 30 more
Caused by: java.lang.IllegalArgumentException: Kerberos principal name does NOT have the expected hostname part: mis@xxx.STORAGE
	at org.apache.hadoop.security.SaslRpcClient.getServerPrincipal(SaslRpcClient.java:325)
	at org.apache.hadoop.security.SaslRpcClient.createSaslClient(SaslRpcClient.java:231)
	at org.apache.hadoop.security.SaslRpcClient.selectSaslClient(SaslRpcClient.java:159)
	at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:394)
	at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:550)
	at org.apache.hadoop.ipc.Client$Connection.access$1800(Client.java:367)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:716)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:712)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1556)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:711)
	... 33 more

**Comment by hungrytortoise** [comment]
@lijiangbo 应该不是这个问题，其他项目验证的时候kerberos的principal  填写的也是mis ，krb5中有相应的适配的。 
会不会是跨集群的原因

**Comment by lijiangbo** [comment]
这个证书在你运行flinkx的机器上可以认证成功吗

**Comment by hungrytortoise** [comment]
可以的

**Comment by hungrytortoise** [comment]
add ：
**flink:1.8.3 \ flinkx:1.8.2 \hadoop：2.6.5**

**Comment by hungrytortoise** [comment]
是不是hdfs-site.xml的某些配置没有导入，导致的

**Comment by oceanos** [comment]
dfs.namenode.kerberos.principal的值，直接从hdfs-site.xml里copy

**Comment by chubbyjiang** [comment]
请问这个问题解决了吗?

**Comment by phoenixhadoop** [comment]
请问这个解决了吗？我也遇到了在非集群节点上Java 用用户的keytab认证成功后往hdfs目录写文件，就报这个错误
