### ISSUE TITLE
Flinkx on yarn 部署出错

### ISSUE THREAD

**Issue by hungrytortoise** [DTStack/flinkx#166]
**Flink1.8.3、hadoop2.6.5 
验证local模式正常，但是on yarn 有如下异常。**

org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot load user class: com.dtstack.flinkx.kafka10.reader.Kafka10InputFormat
ClassLoader info: URL ClassLoader:
    file: '/tmp/blobStore-5eb4d1c3-0360-4e17-8bfd-d5ead09de350/job_189047431279d9f7a13e99fcd19287d5/blob_p-36e1966565d23b84c07db10fdf568aa9b2f2fe4e-2d4fadf9756439ca1256cbc86f0c6736' (valid JAR)
    file: '/home/wls81/var/flinkx/deploy-flinkx/plugins/kafka10reader/flinkx-kafka10-reader-1.8.2.jar' (missing)
    file: '/home/wls81/var/flinkx/deploy-flinkx/plugins/eswriter/flinkx-es-writer-1.8.2.jar' (missing)
    file: '/home/wls81/var/flinkx/deploy-flinkx/plugins/common/flinkx-rdb-reader-1.8.2.jar' (missing)
    file: '/home/wls81/var/flinkx/deploy-flinkx/plugins/common/flinkx-rdb-writer-1.8.2.jar' (missing)
    file: '/home/wls81/var/flinkx/deploy-flinkx/plugins/common/flinkx-rdb-core-1.8.2.jar' (missing)
Class not resolvable through given classloader.
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:236)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:104)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:269)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.dtstack.flinkx.kafka10.reader.Kafka10InputFormat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ChildFirstClassLoader.loadClass(FlinkUserCodeClassLoaders.java:129)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.flink.util.InstantiationUtil$ClassLoaderObjectInputStream.resolveClass(InstantiationUtil.java:78)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:566)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:552)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:540)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:501)
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:224)
	... 4 more

**Comment by hungrytortoise** [comment]
在nodemanager 每个节点的相同目录下都放置部署的包。异常信息上的目录，每个节点都有对应的jar。这个是hadoop版本的问题吗

**Comment by lijiangbo** [comment]
请问任务是怎么提交的
