### ISSUE TITLE
yarn模式，1.5分支

### ISSUE THREAD

**Issue by zhouyunlong** [DTStack/flinkx#17]
10月24号拉了最新1.5代码，flink集群是1.5版本，执行的时候报错，无法提交job到集群，目前报2个错误

1、RestClusterClient - Could not retrieve the web interface URL for the cluster错误？
17:20:36.510 [main] WARN org.apache.flink.client.program.rest.RestClusterClient - Could not retrieve the web interface URL for the cluster.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2237)
	at org.apache.flink.client.program.rest.RestClusterClient.getWebInterfaceURL(RestClusterClient.java:630)
	at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:88)
Caused by: java.util.concurrent.TimeoutException: null
	at org.apache.flink.runtime.concurrent.FutureUtils$Timeout.run(FutureUtils.java:834)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

------------------------------------------------------------------------------------------------------

2、无法提交job
17:20:46.550 [main-SendThread(bd129107:2181)] DEBUG org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x366999882f814c3 after 15ms
17:21:06.540 [main-SendThread(bd129107:2181)] DEBUG org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x366999882f814c3 after 5ms
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: Could not submit job 27c8db013acce632655e8da37eb75a3f.
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:248)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:464)
	at org.apache.flink.client.program.DetachedEnvironment.finalizeExecute(DetachedEnvironment.java:77)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:410)
	at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:97)
Caused by: org.apache.flink.runtime.client.JobSubmissionException: Failed to submit JobGraph.
	at org.apache.flink.client.program.rest.RestClusterClient.lambda$submitJob$5(RestClusterClient.java:357)
	at org.apache.flink.client.program.rest.RestClusterClient$$Lambda$19/291847739.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture$ExceptionCompletion.run(CompletableFuture.java:1246)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:193)
	at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:210)
	at java.util.concurrent.CompletableFuture$ThenApply.run(CompletableFuture.java:723)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:193)
	at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:210)
	at java.util.concurrent.CompletableFuture$ThenCompose.run(CompletableFuture.java:1487)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:193)
	at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:210)
	at java.util.concurrent.CompletableFuture$ThenCombine.run(CompletableFuture.java:882)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:193)
	at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:210)
	at java.util.concurrent.CompletableFuture$ThenApply.run(CompletableFuture.java:723)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:193)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2361)
	at org.apache.flink.runtime.concurrent.FutureUtils$Timeout.run(FutureUtils.java:834)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.CompletionException: org.apache.flink.runtime.concurrent.FutureUtils$RetryException: Could not complete the operation. Exception is not retryable.
	at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:205)
	... 14 more
Caused by: org.apache.flink.runtime.concurrent.FutureUtils$RetryException: Could not complete the operation. Exception is not retryable.
	at org.apache.flink.runtime.concurrent.FutureUtils.lambda$retryOperationWithDelay$5(FutureUtils.java:214)
	at org.apache.flink.runtime.concurrent.FutureUtils$$Lambda$12/288797801.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.doWhenComplete(CompletableFuture.java:2048)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2563)
	at org.apache.flink.runtime.concurrent.FutureUtils.retryOperationWithDelay(FutureUtils.java:196)
	at org.apache.flink.runtime.concurrent.FutureUtils.retryWithDelay(FutureUtils.java:151)
	at org.apache.flink.client.program.rest.RestClusterClient.retry(RestClusterClient.java:694)
	at org.apache.flink.client.program.rest.RestClusterClient.sendRetriableRequest(RestClusterClient.java:682)
	at org.apache.flink.client.program.rest.RestClusterClient.sendRequest(RestClusterClient.java:676)
	at org.apache.flink.client.program.rest.RestClusterClient.sendRequest(RestClusterClient.java:671)
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:317)
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:242)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:464)
	at org.apache.flink.client.program.DetachedEnvironment.finalizeExecute(DetachedEnvironment.java:77)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:410)
	at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:97)
Caused by: java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException

**Comment by yangsishu** [comment]
你把你flink启动的方式发下

**Comment by TdzWork** [comment]
我在standalone模式下也遇到这个问题了
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: Could not submit job 44c89c27eed1b64d974e164efc2c9454.
        at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:247)
        at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:464)
        at org.apache.flink.client.program.DetachedEnvironment.finalizeExecute(DetachedEnvironment.java:77)
        at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:410)
        at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:100)
Caused by: org.apache.flink.runtime.client.JobSubmissionException: Failed to submit JobGraph.
        at org.apache.flink.client.program.rest.RestClusterClient.lambda$submitJob$8(RestClusterClient.java:370)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at org.apache.flink.runtime.concurrent.FutureUtils.lambda$retryOperationWithDelay$5(FutureUtils.java:213)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:929)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.CompletionException: org.apache.flink.runtime.concurrent.FutureUtils$RetryException: Could not complete the operation. Exception is not retryable.
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
        at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
        at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899)
        ... 12 more
Caused by: org.apache.flink.runtime.concurrent.FutureUtils$RetryException: Could not complete the operation. Exception is not retryable.
        ... 10 more
Caused by: java.util.concurrent.CompletionException: org.apache.flink.runtime.rest.util.RestClientException: [Job submission failed.]
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
        at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:953)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
        ... 4 more

**Comment by Horrypotter** [comment]
楼上的兄弟，解决了吗

**Comment by zhouyunlong** [comment]
> 楼上的兄弟，解决了吗

能解决的

**Comment by simenliuxing** [comment]
请问解决了吗？我在代码里加上env.setStateBackend(rockdb或者fs),就不报上名的错，如果不加就没问题，不知道哪里的原因。

**Comment by zhouyunlong** [comment]
解决了




------------------ 原始邮件 ------------------
发件人: "simenliuxing"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 下午3:19
收件人: "DTStack/flinkx"<flinkx@noreply.github.com>;
抄送: "651334919"<651334919@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [DTStack/flinkx] yarn模式，1.5分支 (#17)




请问解决了吗？我在代码里加上env.setStateBackend(rockdb或者fs),就不报上名的错，如果不加就没问题，不知道哪里的原因。

**Comment by simenliuxing** [comment]
能告诉怎么解决的吗？非常感谢

**Comment by zhouyunlong** [comment]
拉的是Master（V1.4.5版本）代码，flink集群版本是1.4，standlone 的HA方式部署的，提交方式时候standlone 。
