### ISSUE TITLE
flink standalone HA模式无法启动任务

### ISSUE THREAD

**Issue by renw7** [DTStack/flinkx#188]
环境是flink1.9 standalone HA 
错误信息如下:
21:48:43.228 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: high-availability.zookeeper.path.root, /flink
21:48:43.228 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: high-availability.cluster-id, /cluster_one
21:48:43.228 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: state.checkpoints.num-retained, 100
21:48:43.229 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: jobmanager.execution.failover-strategy, region
21:48:43.229 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: rest.port, 8081
21:48:43.230 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: jobstore.cache-size, 104857600
21:48:43.230 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: jobstore.expiration-time, 86400
21:48:43.230 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: classloader.resolve-order, parent-first
21:48:43.230 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: task.cancellation.timeout, 0
log4j:WARN No appenders could be found for logger (org.apache.hadoop.metrics2.lib.MutableMetricsFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
21:48:44.573 [main] INFO org.apache.flink.runtime.blob.FileSystemBlobStore - Creating highly available BLOB storage directory at hdfs://134.200.45.42:9000/flink/ha///cluster_one/blob
21:48:44.683 [main] INFO org.apache.flink.runtime.util.ZooKeeperUtils - Enforcing default ACL for ZK connections
21:48:44.684 [main] INFO org.apache.flink.runtime.util.ZooKeeperUtils - Using '/flink/cluster_one' as Zookeeper namespace.
21:48:44.760 [main] INFO org.apache.flink.shaded.curator.org.apache.curator.framework.imps.CuratorFrameworkImpl - Starting
21:48:44.768 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Client environment:zookeeper.version=3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f, built on 03/23/2017 10:13 GMT
21:48:44.768 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Client environment:host.name=hb-bd-rp-001
21:48:44.768 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Client environment:java.version=1.8.0_181
21:48:44.768 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Client environment:java.vendor=Oracle Corporation
21:48:44.768 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Client environment:java.home=/usr/local/java/jdk1.8.0_181/jre
21:48:44.768 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Client environment:java.class.path=/home/flinkapp/flinkx/lib/flinkx-launcher-1.6.jar
21:48:44.768 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
21:48:44.769 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Client environment:java.io.tmpdir=/tmp
21:48:44.769 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Client environment:java.compiler=<NA>
21:48:44.769 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Client environment:os.name=Linux
21:48:44.769 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Client environment:os.arch=amd64
21:48:44.769 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Client environment:os.version=3.10.0-123.el7.x86_64
21:48:44.769 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Client environment:user.name=flinkapp
21:48:44.769 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Client environment:user.home=/home/flinkapp
21:48:44.769 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/home/flinkapp/flinkx/work
21:48:44.770 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=134.200.11.41:2181,134.200.11.42:2181,134.200.11.43:2181,134.200.11.44:2181 sessionTimeout=60000 watcher=org.apache.flink.shaded.curator.org.apache.curator.ConnectionState@24faea88
21:48:44.787 [main-SendThread(134.200.11.43:2181)] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Opening socket connection to server 134.200.11.43/134.200.11.43:2181. Will not attempt to authenticate using SASL (unknown error)
21:48:44.788 [main-SendThread(134.200.11.43:2181)] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Socket connection established to 134.200.11.43/134.200.11.43:2181, initiating session
21:48:44.796 [main-SendThread(134.200.11.43:2181)] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Session establishment complete on server 134.200.11.43/134.200.11.43:2181, sessionid = 0x36f40de4d990543, negotiated timeout = 40000
21:48:44.808 [main-EventThread] INFO org.apache.flink.shaded.curator.org.apache.curator.framework.state.ConnectionStateManager - State change: CONNECTED
21:48:45.235 [main] INFO org.apache.flink.runtime.rest.RestClient - Rest client endpoint started.
21:48:45.239 [main] INFO org.apache.flink.runtime.leaderretrieval.ZooKeeperLeaderRetrievalService - Starting ZooKeeperLeaderRetrievalService /leader/rest_server_lock.
21:48:45.277 [main] INFO org.apache.flink.runtime.leaderretrieval.ZooKeeperLeaderRetrievalService - Starting ZooKeeperLeaderRetrievalService /leader/dispatcher_lock.
21:48:45.282 [main] INFO org.apache.flink.runtime.leaderretrieval.ZooKeeperLeaderRetrievalService - Starting ZooKeeperLeaderRetrievalService /leader/dispatcher_lock.
21:48:45.320 [main] INFO org.apache.flink.runtime.leaderretrieval.ZooKeeperLeaderRetrievalService - Stopping ZooKeeperLeaderRetrievalService /leader/dispatcher_lock.
21:48:45.355 [main] INFO org.apache.flink.client.program.rest.RestClusterClient - Starting program in interactive mode (detached: true)
21:48:45.384 [main] INFO com.dtstack.flinkx.Main - Open checkpoint with interval:60000
21:48:45.396 [main] INFO com.dtstack.flinkx.classloader.ClassLoaderManager - jarUrl:file:/home/flinkapp/flinkx/plugins/common/flinkx-rdb-core-release_1.8.5.jar_file:/home/flinkapp/flinkx/plugins/common/flinkx-rdb-reader-release_1.8.5.jar_file:/home/flinkapp/flinkx/plugins/common/flinkx-rdb-writer-release_1.8.5.jar_file:/home/flinkapp/flinkx/plugins/oraclereader/flinkx-oracle-reader-release_1.8.5.jar create ClassLoad successful...
21:48:45.448 [main] INFO org.apache.flink.api.java.typeutils.TypeExtractor - class org.apache.flink.types.Row does not contain a getter for field fields
21:48:45.448 [main] INFO org.apache.flink.api.java.typeutils.TypeExtractor - class org.apache.flink.types.Row does not contain a setter for field fields
21:48:45.448 [main] INFO org.apache.flink.api.java.typeutils.TypeExtractor - Class class org.apache.flink.types.Row cannot be used as a POJO type because not all fields are valid POJO fields, and must be processed as GenericType. Please read the Flink documentation on "Data Types & Serialization" for details of the effect on performance.
21:48:45.516 [main] INFO com.dtstack.flinkx.classloader.ClassLoaderManager - jarUrl:file:/home/flinkapp/flinkx/plugins/common/flinkx-rdb-core-release_1.8.5.jar_file:/home/flinkapp/flinkx/plugins/common/flinkx-rdb-reader-release_1.8.5.jar_file:/home/flinkapp/flinkx/plugins/common/flinkx-rdb-writer-release_1.8.5.jar_file:/home/flinkapp/flinkx/plugins/eswriter/flinkx-es-writer-release_1.8.5.jar create ClassLoad successful...
21:48:45.712 [main] WARN org.apache.flink.streaming.api.environment.StreamContextEnvironment - Job was executed in detached mode, the results will be available on completion.
21:48:45.786 [main] INFO org.apache.flink.client.program.rest.RestClusterClient - Submitting job 4d8f065939c7702896a5006c7ceb4415 (detached: true).
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: Could not submit job (JobID: 4d8f065939c7702896a5006c7ceb4415)
        at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:250)
        at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:483)
        at org.apache.flink.client.program.DetachedEnvironment.finalizeExecute(DetachedEnvironment.java:77)
        at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:429)
        at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:115)
Caused by: org.apache.flink.runtime.client.JobSubmissionException: Failed to submit JobGraph.
        at org.apache.flink.client.program.rest.RestClusterClient.lambda$submitJob$8(RestClusterClient.java:388)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at org.apache.flink.runtime.concurrent.FutureUtils.lambda$retryOperationWithDelay$5(FutureUtils.java:208)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:929)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.flink.runtime.rest.util.RestClientException: [Failed to deserialize JobGraph.]
        at org.apache.flink.runtime.rest.RestClient.parseResponse(RestClient.java:389)
        at org.apache.flink.runtime.rest.RestClient.lambda$submitRequest$3(RestClient.java:373)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
        ... 4 more

json是个简单的例子，local下测试没问题

**Comment by FlechazoW** [comment]
This issue has been too long to review it and reopen new one if necessary
