### ISSUE TITLE
mysql->mysql standalone模式按照QuickStart提示编译，提交到flink提示：java.lang.NoClassDefFoundError: org/apache/commons/net/telnet/TelnetClient，反复编译多次也是失败

### ISSUE THREAD

**Issue by tcphl** [DTStack/flinkx#201]
启动命令: ./bin/flinkx -mode standalone -job /usr/local/flinkx/myexamples/mysqlTest.json -pluginRoot /usr/local/flinkx/flinkx/plugins -flinkconf $FLINK_HOME/conf

Flinkx本地日志：
15:02:01.655 [main] INFO com.dtstack.flinkx.classloader.ClassLoaderManager - jarUrl:file:/usr/local/flinkx/flinkx/plugins/common/flinkx-rdb-core-release_1.8.5.jar_file:/usr/local/flinkx/flinkx/plugins/common/flinkx-rdb-reader-release_1.8.5.jar_file:/usr/local/flinkx/flinkx/plugins/common/flinkx-rdb-writer-release_1.8.5.jar_file:/usr/local/flinkx/flinkx/plugins/mysqlwriter/flinkx-mysql-writer-release_1.8.5.jar create ClassLoad successful...

从flink集群上可以看到任务成功提交，但是最后都是失败，从flInk的JobManage中的日志看到错误堆栈信息如下:

java.lang.NoClassDefFoundError: org/apache/commons/net/telnet/TelnetClient
	at com.dtstack.flinkx.util.TelnetUtil$1.call(TelnetUtil.java:49)
	at com.dtstack.flinkx.util.TelnetUtil$1.call(TelnetUtil.java:44)
	at com.dtstack.flinkx.util.RetryUtil$Retry.call(RetryUtil.java:126)
	at com.dtstack.flinkx.util.RetryUtil$Retry.doRetry(RetryUtil.java:73)
	at com.dtstack.flinkx.util.RetryUtil.executeWithRetry(RetryUtil.java:53)
	at com.dtstack.flinkx.util.TelnetUtil.telnet(TelnetUtil.java:44)
	at com.dtstack.flinkx.util.TelnetUtil.telnet(TelnetUtil.java:97)
	at com.dtstack.flinkx.rdb.util.DbUtil.getConnectionInternal(DbUtil.java:107)
	at com.dtstack.flinkx.rdb.util.DbUtil.getConnection(DbUtil.java:135)
	at com.dtstack.flinkx.rdb.outputformat.JdbcOutputFormat.openInternal(JdbcOutputFormat.java:135)
	at com.dtstack.flinkx.outputformat.BaseRichOutputFormat.open(BaseRichOutputFormat.java:227)
	at com.dtstack.flinkx.streaming.api.functions.sink.DtOutputFormatSinkFunction.open(DtOutputFormatSinkFunction.java:88)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:424)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:290)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jh290948587** [comment]
我遇到了同样的问题，有解决方案了吗

**Comment by tcphl** [comment]
去Flink官网下载hadoop的组件添加到Flink的lib文件夹下，重启Flink，问题解决,

**Comment by baoziaichiyu** [comment]
flinkx-clients-master.jar 放入flink下的lib中

**Comment by tcphl** [comment]
收到

**Comment by baoziaichiyu** [comment]
一直好奇standalone模式下 为什么已经java -cp flinkx-clients-master.jar包了 没用。只能手动放入fLink lib中
