### ISSUE TITLE
使用yarnPer 模式提交任务失败

### ISSUE THREAD

**Issue by williams7111** [DTStack/flinkx#203]
hadoop版本：3.1.3
flink版本：1.9.1
flinkx版本：1.8
使用命令：
`./flinkx -mode yarnPer -job testjson/kates.json -flinkconf /opt/flink/conf/ -yarnconf /opt/hadoop/etc/hadoop/ -flinkLibJar /opt/flink/lib`

已测试flink on yarn的样例运行正常，环境未发现问题

异常如下

```
22:55:52.276 [main] WARN org.apache.flink.yarn.AbstractYarnClusterDescriptor - The JobManager or TaskManager memory is below the smallest possible YARN Container size. The value of 'yarn.scheduler.minimum-allocation-mb' is '1024'. Please increase the memory size.YARN wi
ll allocate the smaller containers but the scheduler will account for the minimum-allocation-mb, maybe not all instances you requested will start.
22:55:52.276 [main] INFO org.apache.flink.yarn.AbstractYarnClusterDescriptor - Cluster specification: ClusterSpecification{masterMemoryMB=1024, taskManagerMemoryMB=1024, numberTaskManagers=1, slotsPerTaskManager=1, priority=0}
22:55:52.535 [main] WARN org.apache.flink.yarn.AbstractYarnClusterDescriptor - The configuration directory ('/opt/flink/conf/') contains both LOG4J and Logback configuration files. Please delete or rename one of them.
22:55:58.006 [main] INFO org.apache.flink.yarn.AbstractYarnClusterDescriptor - Submitting application master application_1588082364015_0002
22:55:58.029 [main] INFO org.apache.flink.yarn.AbstractYarnClusterDescriptor - Waiting for the cluster to be allocated
22:55:58.032 [main] INFO org.apache.flink.yarn.AbstractYarnClusterDescriptor - Deploying cluster, current state ACCEPTED
Exception in thread "main" org.apache.flink.client.deployment.ClusterDeploymentException: Could not deploy Yarn job cluster.
	at org.apache.flink.yarn.YarnClusterDescriptor.deployJobCluster(YarnClusterDescriptor.java:82)
	at com.dtstack.flinkx.launcher.perjob.PerJobSubmitter.submit(PerJobSubmitter.java:89)
	at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:139)
Caused by: org.apache.flink.yarn.AbstractYarnClusterDescriptor$YarnDeploymentException: The YARN application unexpectedly switched to state FAILED during deployment. 
Diagnostics from YARN: Application application_1588082364015_0002 failed 1 times (global limit =2; local limit is =1) due to AM Container for appattempt_1588082364015_0002_000001 exited with  exitCode: 1
Failing this attempt.Diagnostics: [2020-04-28 22:56:04.052]Exception from container-launch.
Container id: container_1588082364015_0002_01_000001
Exit code: 1

[2020-04-28 22:56:04.054]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :

[2020-04-28 22:56:04.056]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :

For more detailed output, check the application tracking page: http://node1:8088/cluster/app/application_1588082364015_0002 Then click on links to logs of each attempt.
. Failing the application.
If log aggregation is enabled on your cluster, use this command to further investigate the issue:
yarn logs -applicationId application_1588082364015_0002
	at org.apache.flink.yarn.AbstractYarnClusterDescriptor.startAppMaster(AbstractYarnClusterDescriptor.java:1167)
	at org.apache.flink.yarn.AbstractYarnClusterDescriptor.deployInternal(AbstractYarnClusterDescriptor.java:500)
	at org.apache.flink.yarn.YarnClusterDescriptor.deployJobCluster(YarnClusterDescriptor.java:75)
	... 2 more
22:56:04.168 [Thread-85] INFO org.apache.flink.yarn.AbstractYarnClusterDescriptor - Cancelling deployment from Deployment Failure Hook
22:56:04.169 [Thread-85] INFO org.apache.flink.yarn.AbstractYarnClusterDescriptor - Killing YARN application
22:56:04.280 [Thread-85] INFO org.apache.flink.yarn.AbstractYarnClusterDescriptor - Deleting files in hdfs://localhost:9000/user/root/.flink/application_1588082364015_0002
```

**Comment by kanata163** [comment]
@williams7111 
FlinkX与Flink的版本必须要保持一致，如果1.8不满足你的需求的话，你可以考虑升级到1.10。

**Comment by kanata163** [comment]
@williams7111 
FlinkX与Flink的版本必须要保持一致，如果1.8不满足你的需求的话，你可以考虑升级到1.10。
