### ISSUE TITLE
flinkx yarnPer模式启动报错

### ISSUE THREAD

**Issue by LoveXiaoQuan** [DTStack/flinkx#213]
在多套环境上都出现这个启动问题，帮忙看一下,谢谢
启动命令如下:
bin/flinkx -mode yarnPer -job kafka11_to_hive.json -pluginRoot /root/flinkx/syncplugins -flinkconf $FLINK_HOME/conf -yarnconf $HADOOP_HOME/etc/hadoop -flinkLibJar $FLINK_HOME/lib -pluginLoadMode shipfile
报错如下:
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/app/hadoop-2.7.3/hdfs/tmp/nm-local-dir/usercache/root/appcache/application_1589891468103_0003/filecache/19/flinkx-hive-writer-release_1.10.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/app/hadoop-2.7.3/hdfs/tmp/nm-local-dir/usercache/root/appcache/application_1589891468103_0003/filecache/11/flinkx-release_1.10.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/app/hadoop-2.7.3/hdfs/tmp/nm-local-dir/usercache/root/appcache/application_1589891468103_0003/filecache/18/slf4j-log4j12-1.7.15.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/app/hadoop-2.7.3/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:ERROR setFile(null,false) call failed.
java.io.FileNotFoundException:  (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:64)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.<clinit>(ClusterEntrypoint.java:104)

**Comment by kanata163** [comment]
你$FLINK_HOME/conf/目录下有log4j的配置文件吗？

**Comment by LoveXiaoQuan** [comment]
你好 有的&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kanata163"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月19日(星期二) 晚上9:44
收件人:&nbsp;"DTStack/flinkx"<flinkx@noreply.github.com&gt;;
抄送:&nbsp;"怪兽大叔"<1119593634@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DTStack/flinkx] flinkx yarnPer模式启动报错 (#213)





 
你$FLINK_HOME/conf/目录下有log4j的配置文件吗？

**Comment by LoveXiaoQuan** [comment]
请问下如何在不删除conf目录下log4j的配置文件保证正常运行
因为公司的配置不能删除，有什么其他的解决办法吗，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"怪兽大叔"<1119593634@qq.com&gt;;
发送时间:&nbsp;2020年5月19日(星期二) 晚上9:47
收件人:&nbsp;"DTStack/flinkx"<reply@reply.github.com&gt;;"DTStack/flinkx"<flinkx@noreply.github.com&gt;;
抄送:&nbsp;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;回复： [DTStack/flinkx] flinkx yarnPer模式启动报错 (#213)



你好 有的 
------------------ 原始邮件 ------------------
发件人:&nbsp;"kanata163"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月19日(星期二) 晚上9:44
收件人:&nbsp;"DTStack/flinkx"<flinkx@noreply.github.com&gt;;
抄送:&nbsp;"怪兽大叔"<1119593634@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DTStack/flinkx] flinkx yarnPer模式启动报错 (#213)





 
你$FLINK_HOME/conf/目录下有log4j的配置文件吗？

**Comment by Level1Accelerator** [comment]
我也有这个问题

**Comment by LoveXiaoQuan** [comment]
flinkx启动的时候把log4j的配置去掉就行了





------------------ 原始邮件 ------------------
发件人: Level1Accelerator <notifications@github.com&gt;
发送时间: 2020年5月25日 15:06
收件人: DTStack/flinkx <flinkx@noreply.github.com&gt;
抄送: LoveXiaoQuan <1119593634@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[DTStack/flinkx] flinkx yarnPer模式启动报错 (#213)





 
我也有这个问题
