### ISSUE TITLE
"column": ["*"] 和 "customSql":"select .... from test.from1" 同时存在时，报IndexOutOfBoundsException

### ISSUE THREAD

**Issue by gk0916** [DTStack/flinkx#224]
json file:
```
    "column": ["*"],
    "customSql":"select id,name,age from test.from1",
```

The fllowing is error log:
```
8:31:05.144 [Source: mysqlreader -> Sink: mysqlwriter (1/1)] INFO com.dtstack.flinkx.mysql.format.MysqlInputFormat - JdbcInputFormat[Flink Streaming Job]open: end
08:31:05.148 [Source: mysqlreader -> Sink: mysqlwriter (1/1)] ERROR com.dtstack.flinkx.mysql.format.MysqlInputFormat - error to get next record, row = 1,null, descColumnTypeList = ["*"], e = java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.dtstack.flinkx.mysql.format.MysqlInputFormat.nextRecordInternal(MysqlInputFormat.java:108)
	at com.dtstack.flinkx.inputformat.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:251)
	at com.dtstack.flinkx.inputformat.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:57)
	at com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:135)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:93)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:57)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.run(SourceStreamTask.java:97)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gk0916** [comment]
> json file:
> 
> ```
>     "column": ["*"],
>     "customSql":"select id,name,age from test.from1",
> ```
> 
> The fllowing is error log:
> 
> ```
> 8:31:05.144 [Source: mysqlreader -> Sink: mysqlwriter (1/1)] INFO com.dtstack.flinkx.mysql.format.MysqlInputFormat - JdbcInputFormat[Flink Streaming Job]open: end
> 08:31:05.148 [Source: mysqlreader -> Sink: mysqlwriter (1/1)] ERROR com.dtstack.flinkx.mysql.format.MysqlInputFormat - error to get next record, row = 1,null, descColumnTypeList = ["*"], e = java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
> 	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
> 	at java.util.ArrayList.get(ArrayList.java:433)
> 	at com.dtstack.flinkx.mysql.format.MysqlInputFormat.nextRecordInternal(MysqlInputFormat.java:108)
> 	at com.dtstack.flinkx.inputformat.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:251)
> 	at com.dtstack.flinkx.inputformat.BaseRichInputFormat.nextRecord(BaseRichInputFormat.java:57)
> 	at com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:135)
> 	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:93)
> 	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:57)
> 	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.run(SourceStreamTask.java:97)
> 	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)
> 	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
> 	at java.lang.Thread.run(Thread.java:748)
> ```

and reader is mysqlreader , writer is mysqlwriter

**Comment by kanata163** [comment]
@gk0916 
这里确实存在这样的问题，在你的pull request中我们给出了反馈与建议，请查看。
