### ISSUE TITLE
关于hive无法写入的问题

### ISSUE THREAD

**Issue by chenaiyuan** [DTStack/flinkx#251]
您好 我在写入hive的时候 几经波折，一直报：
WARN org.apache.hadoop.ipc.Client - Couldn't setup connection for ******
javax.security.sasl.SaslException: No common protection layer between client and server
但是实际应该是这块儿的问题：（源代码）
protected void checkOutputDir() {
        try{
            Path dir = new Path(outputFilePath);

            （问题发生位置） if(fs.exists(dir)){
                if(fs.isFile(dir)){
                    throw new RuntimeException("Can't write new files under common file: " + dir + "\n"
                            + "One can only write new files under directories");
                }
            }
请问这里的路径验证，是和哪点儿有关？我的json文件的哪个参数么？？

**Comment by kanata163** [comment]
把你的日志信息和json脚本发一下吧

**Comment by chenaiyuan** [comment]
"writer": {
          "name" : "hivewriter",
          "parameter" : {
            
            "jdbcUrl" : "jdbc:hive2://****:10000/db1;principal=hive/hadoop.****_5cd8_4158_b0e5_b01acd2e99aa.com@****_5CD8_4158_B0E5_B01ACD2E99AA.COM",
            "username" : "",
            "password" : "",
            "fileType" : "text",
            "fieldDelimiter" : "\u0001",
            "writeMode" : "overwrite",
            "compress" : "",
            "charsetName" : "UTF-8",
            "maxFileSize" : 1073741824,
            "tablesColumn" : "{\"test\":[{\"key\":\"id\",\"type\":\"bigint\"},{\"key\":\"name\",\"type\":\"string\"},{\"key\":\"location\",\"type\":\"string\"},{\"key\":\"duration\",\"type\":\"int\"},{\"key\":\"time\",\"type\":\"timestamp\"}]}",
            
            "partition" : "pt",
            "partitionType" : "DAY",
            "defaultFS" : "hdfs://hacluster",
			"hadoopConfig":{
				 "dfs.ha.namenodes.hacluster": "27,28",
				 "dfs.namenode.rpc-address.hacluster.27": "***:9820",
				 "dfs.client.failover.proxy.provider.hacluster": "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider",
				 "dfs.namenode.rpc-address.hacluster.28": "***:9820",
				 "dfs.nameservices": "hacluster",
				 "hadoop.security.authorization": "true",
				 "useLocalFile": true,
				 "hadoop.security.authentication": "Kerberos",
				 "dfs.namenode.kerberos.principal": "hdfs/*****_5cd8_4158_b0e5_b01acd2e99aa.com@*****_B0E5_B01ACD2E99AA.COM",
				 "dfs.namenode.keytab.file": "D:\\tmp\\flinkx\\keytab\\user.keytab",
				 "principalFile": "D:\\tmp\\flinkx\\keytab\\user.keytab",
				 "java.security.krb5.conf": "D:\\tmp\\flinkx\\keytab\\krb5.conf"
			}
		  }
		}
我是在本地跑的 这些hadoop的配置应该没问题 因为这个test表都已经在远程上建了，只是数据没写进去。
WARN org.apache.hadoop.ipc.Client - Couldn't setup connection for test@****_5CD8_4158_B0E5_B01ACD2E99AA.COM to node-master****/*****:9820
javax.security.sasl.SaslException: No common protection layer between client and server
	at com.sun.security.sasl.gsskerb.GssKrb5Client.doFinalHandshake(GssKrb5Client.java:251)
	at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:186)
	at org.apache.hadoop.security.SaslRpcClient.saslEvaluateToken(SaslRpcClient.java:483)
	at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:427)
	at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:560)
	at org.apache.hadoop.ipc.Client$Connection.access$1900(Client.java:375)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:729)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:725)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:725)
	at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:375)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1528)
	at org.apache.hadoop.ipc.Client.call(Client.java:1451)
	at org.apache.hadoop.ipc.Client.call(Client.java:1412)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy27.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:771)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy28.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:2108)
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1305)
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1317)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1426)
	at com.dtstack.flinkx.hdfs.writer.BaseHdfsOutputFormat.checkOutputDir(BaseHdfsOutputFormat.java:82)
	at com.dtstack.flinkx.outputformat.BaseFileOutputFormat.actionBeforeWriteData(BaseFileOutputFormat.java:139)
	at com.dtstack.flinkx.outputformat.BaseFileOutputFormat.openInternal(BaseFileOutputFormat.java:104)
	at com.dtstack.flinkx.hdfs.writer.BaseHdfsOutputFormat.openInternal(BaseHdfsOutputFormat.java:74)
	at com.dtstack.flinkx.outputformat.BaseRichOutputFormat.open(BaseRichOutputFormat.java:227)
	at com.dtstack.flinkx.hive.writer.HiveOutputFormat.createHdfsOutputFormat(HiveOutputFormat.java:268)
	at com.dtstack.flinkx.hive.writer.HiveOutputFormat.getHdfsOutputFormat(HiveOutputFormat.java:248)
	at com.dtstack.flinkx.hive.writer.HiveOutputFormat.writeRecord(HiveOutputFormat.java:198)
	at com.dtstack.flinkx.hive.writer.HiveOutputFormat.writeRecord(HiveOutputFormat.java:49)
	at com.dtstack.flinkx.streaming.api.functions.sink.DtOutputFormatSinkFunction.invoke(DtOutputFormatSinkFunction.java:110)
	at org.apache.flink.streaming.api.functions.sink.SinkFunction.invoke(SinkFunction.java:52)
	at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:56)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:579)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:554)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:534)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:718)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator$CountingOutput.collect(AbstractStreamOperator.java:696)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$NonTimestampContext.collect(StreamSourceContexts.java:104)
	at com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:137)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:93)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:57)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.run(SourceStreamTask.java:97)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:745)

**Comment by chenaiyuan** [comment]
@kanata163
