### ISSUE TITLE
请问什么时候支持Oracle logminer的CDC实时处理呀？

### ISSUE THREAD

**Issue by liuhouer** [DTStack/flinkx#284]
请问什么时候支持Oracle logminer的CDC实时处理呀？
现在只支持Oracle批量处理

**Comment by kanata163** [comment]
@liuhouer 已支持

**Comment by ithjz** [comment]
没看到代码在哪里呀?

**Comment by ithjz** [comment]
oraclelogminerreader 搜索不到代码

**Comment by yanghuaiGit** [comment]
下载最新代码

**Comment by liuhouer** [comment]
我这里有个问题，下载1.11release版本，编译也通过了，不过跑local模式运行oracle都通不过，提示找不到OraclelogminerReader

我看源码的打包类路径是：com.dtstack.flinkx.oracle.reader.OracleReader

读取的却是com.dtstack.flinkx.oraclelogminer.reader.OraclelogminerReader 这是没经过测试吧？
1.10版本也是这个包名

`Caused by: java.lang.ClassNotFoundException: com.dtstack.flinkx.oraclelogminer.reader.OraclelogminerReader
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.dtstack.flinkx.reader.DataReaderFactory.lambda$getDataReader$0(DataReaderFactory.java:47)
        at com.dtstack.flinkx.classloader.ClassLoaderSupplierCallBack.callbackAndReset(ClassLoaderSupplierCallBack.java:33)
        at com.dtstack.flinkx.classloader.ClassLoaderManager.newInstance(ClassLoaderManager.java:50)
        at com.dtstack.flinkx.reader.DataReaderFactory.getDataReader(DataReaderFactory.java:46)
        ... 2 more`
