### ISSUE TITLE
同步的时候遇到这gc时间太短

### ISSUE THREAD

**Issue by yelijun** [DTStack/flinkx#30]
java.io.IOException: Couldn't read data - GC life time is shorter than transaction duration, transaction starts at 2019-02-18 16:10:52.016 +0800 CST, GC safe point is 2019-02-18 16:29:41.316 +0800 CST

这个配置是否可以修改？

ps：flinkx 同步mysql数据的时候 每次从mysql拽多少行数据？

**Comment by yangsishu** [comment]
现在是默认读取1000行，现在还不支持配置

**Comment by yangsishu** [comment]
你的mysql是什么版本

**Comment by yelijun** [comment]
谢谢回答我的问题。

我用的版本信息：5.7.10 

我之前用release里面的1.5 只能local
现在用了branch里面的 1.5 能用standalone 但是还是不支持 yarn
使用yarn 会提示：

> 16:01:06.836 [main] DEBUG org.apache.hadoop.security.authentication.util.KerberosName - Kerberos krb5 configuration not found, setting default realm to empty
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: No flink session found on yarn cluster.
        at com.dtstack.flinkx.launcher.ClusterClientFactory.createYarnClient(ClusterClientFactory.java:126)
        at com.dtstack.flinkx.launcher.ClusterClientFactory.createClusterClient(ClusterClientFactory.java:57)
        at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:87)
Caused by: java.lang.RuntimeException: No flink session found on yarn cluster.
        at com.dtstack.flinkx.launcher.ClusterClientFactory.createYarnClient(ClusterClientFactory.java:111)
        ... 2 more
这个kerbose 是默认开启的 还是说我哪里配置不对？
我并没有配置这个kerbose

**Comment by yelijun** [comment]
![image](https://user-images.githubusercontent.com/3347175/52956592-8b00b300-33ca-11e9-9d6a-a9da93758126.png)

> java.io.IOException: Couldn't read data - Application was streaming results when the connection failed. Consider raising value of 'net_write_timeout' on the server.
	at com.dtstack.flinkx.rdb.inputformat.JdbcInputFormat.nextRecordInternal(JdbcInputFormat.java:275)
	at com.dtstack.flinkx.inputformat.RichInputFormat.nextRecord(RichInputFormat.java:82)
	at com.dtstack.flinkx.inputformat.RichInputFormat.nextRecord(RichInputFormat.java:44)
	at org.apache.flink.streaming.api.functions.source.InputFormatSourceFunction.run(InputFormatSourceFunction.java:91)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:94)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:58)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.run(SourceStreamTask.java:99)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:306)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:712)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Application was streaming results when the connection failed. Consider raising value of 'net_write_timeout' on the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3462)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3903)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:1999)
	at com.mysql.jdbc.RowDataDynamic.nextRecord(RowDataDynamic.java:374)
	at com.mysql.jdbc.RowDataDynamic.next(RowDataDynamic.java:354)
	at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:6312)
	at com.dtstack.flinkx.rdb.inputformat.JdbcInputFormat.nextRecordInternal(JdbcInputFormat.java:272)
	... 9 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
	at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144)
	at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3011)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3522)
	... 17 more

在standalone 模式下 大概同步了
![image](https://user-images.githubusercontent.com/3347175/52956667-d4e99900-33ca-11e9-865a-4bf7fdca9226.png)
![image](https://user-images.githubusercontent.com/3347175/52956708-ecc11d00-33ca-11e9-9429-03815ce4290d.png)

然后就抛异常了。

我们现在想做的是把mysql的大表 有好几亿的数据同步到hdfs上，目前还没有成功

**Comment by yangsishu** [comment]
5.7版本的mysql还没有适配过，现在我们这边测试的都是5.6

**Comment by yelijun** [comment]
okay, 谢谢。

我们再找别的办法 做这个全量同步（数据量 6-7亿），你们这边有什么建议吗？

**Comment by yangsishu** [comment]
同步开启多并发，是要设置切分键的，要不然是没效果的

**Comment by yangsishu** [comment]
我看你截的图，虽然设置了4个并发，其实只有一个通道在读

**Comment by yangsishu** [comment]
https://github.com/DTStack/flinkx/blob/master/docs/mysqlreader.md 看这个里面的splitpk 介绍

**Comment by yelijun** [comment]
好的，我先看看这个切分，非常感谢

**Comment by yelijun** [comment]
![image](https://user-images.githubusercontent.com/3347175/52986376-6809e980-3432-11e9-9cef-c353690e028c.png)
![image](https://user-images.githubusercontent.com/3347175/52986380-693b1680-3432-11e9-9997-06ec07ee1365.png)

这个我有设置的，只是好像没有起效
