### ISSUE TITLE
hbase为数据源时，显示报错hbaseConfig不能为空Map结构

### ISSUE THREAD

**Issue by havenBoy** [DTStack/flinkx#302]
报错如下：
java.lang.IllegalArgumentException: hbaseConfig不能为空Map结构!
                at org.apache.commons.lang3.Validate.isTrue(Validate.java:155)
                at com.dtstack.flinkx.hbase.HbaseHelper.getHbaseConnection(HbaseHelper.java:58)
                at com.dtstack.flinkx.hbase.reader.HbaseInputFormat.openInputFormat(HbaseInputFormat.java:90)
                at com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:127)
                at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:93)
                at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:57)
                at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.run(SourceStreamTask.java:97)
                at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:300)
                at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
                at java.lang.Thread.run(Thread.java:748)

任务json展示如下
{"job":{"content":[{"reader":{"parameter":{"mode":"normal","scanCacheSize":256,"scanBatchSize":100,"column":[{"name":"m_id:name","type":"STRING"}],"encodig":"UTF-8","table":"zh","hbaseConfig":{"hbase.zookeeper.quorum":"node1,node3,node2","hbase.zookeeper.property.clientPort":"2181","hbase.security.authorization":false,"zookeeper.znode.parent":"/hbase-unsecure","hbase.rootdir":"hdfs://apps/hbase/data","hbase.cluster.distributed":"true"}},"name":"hbasereader"},"writer":{"parameter":{"password":"******","column":[{"name":"name","type":"VARCHAR"}],"connection":[{"jdbcUrl":["jdbc:mysql://10.58.56.214:3306/data_factory"],"table":["student"]}],"writeMode":"update","batchSize":1024,"username":"factory"},"name":"mysqlwriter"}}],"setting":{"restore":{"maxRowNumForCheckpoint":1000,"isRestore":false,"restoreColumnName":"id","restoreColumnIndex":-1},"log":{"isLogger":true},"speed":{"bytes":0,"channel":1}}}}

**Comment by kanata163** [comment]
@havenBoy 
你的FlinkX是最新的吗？如果不是，请更新。

**Comment by havenBoy** [comment]
是我自己的问题，代码不是最新的
