### ISSUE TITLE
flinkx1.10.4-release kafka11reader GenericInputSplit强转KafkaInputSplit报错

### ISSUE THREAD

**Issue by Dashiliu** [DTStack/flinkx#309]
在试用flinkx1.10.4-release过程中,试用kafka11reader读入数据并打印报错

java.lang.ClassCastException: org.apache.flink.core.io.GenericInputSplit cannot be cast to com.dtstack.flinkx.kafkabase.KafkaInputSplit
        at com.dtstack.flinkx.kafkabase.format.KafkaBaseInputFormat.openInternal(KafkaBaseInputFormat.java:100)
        at com.dtstack.flinkx.inputformat.BaseRichInputFormat.open(BaseRichInputFormat.java:171)
        at com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:124)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63)
        at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:196)
----------------------------
目前把涉及到强转的位置都传入null,不影响09 10 11的kafkareader,已经能正常运行,
请问下社区大佬为啥不用flink自带的kafka输入?可以把这个功能描述一下吗,我也想进行一些二次开发

**Comment by kanata163** [comment]
提交到yarn上时，flink配置文件设置 classloader.resolve-order: parent-first
