### ISSUE TITLE
on yarn 模式 channel 设置超过5 就会报错

### ISSUE THREAD

**Issue by yelijun** [DTStack/flinkx#35]
org.apache.flink.streaming.runtime.tasks.StreamTaskException: Could not instantiate outputs in order.

> org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot load user class: ch.qos.logback.classic.Logger
ClassLoader info: URL ClassLoader:
    file: '/data3/yarn/nm/usercache/root/appcache/application_1544768545362_0843/blobStore-8adb0e17-dc6d-4483-9bf3-c9e17218fff4/job_0be51bf30c1876bac50876dcda78602d/blob_p-09ff3108ffc810d694ec5cf7e4370b8ea3b81890-68d3a95ce8b51258378b6a941c71e486' (valid JAR)
    file: '/data/software/flinkx/plugins/mysqlreader/flinkx-mysql-reader.jar' (valid JAR)
    file: '/data/software/flinkx/plugins/hdfswriter/flinkx-hdfs-writer.jar' (valid JAR)
    file: '/data/software/flinkx/plugins/common/flinkx-rdb.jar' (valid JAR)
Class not resolvable through given classloader.
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:236)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:104)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:267)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:704)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ChildFirstClassLoader.loadClass(FlinkUserCodeClassLoaders.java:120)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.flink.util.InstantiationUtil$ClassLoaderObjectInputStream.resolveClass(InstantiationUtil.java:78)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1826)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)

> org.apache.flink.streaming.runtime.tasks.StreamTaskException: Could not instantiate outputs in order.
	at org.apache.flink.streaming.api.graph.StreamConfig.getOutEdgesInOrder(StreamConfig.java:398)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.createStreamRecordWriters(StreamTask.java:1164)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.<init>(StreamTask.java:212)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.<init>(StreamTask.java:190)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.<init>(SourceStreamTask.java:51)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.flink.runtime.taskmanager.Task.loadAndInstantiateInvokable(Task.java:1398)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:682)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.Logger

`
"job": {
  3     "setting": {
  4       "speed": {
  5         "channel": xxx
  6       },
`
channel 一多就会有这个错误
如果设置小 比如 4就能正常， 设置成5的时候 偶尔正常执行

**Comment by yangsishu** [comment]
那个分支

**Comment by yangsishu** [comment]
是yarnsession 模式吗，看下每个节点的jar是不是一样的

**Comment by yelijun** [comment]
提交yarn-session的 机器上 flink 版本 1.7
flinkx版本 v1.7.0_dev

其他节点flinkx版本：v1.5.0

由于之前 flink 1.7一下的版本启动yarn session 都不能执行同步任务。
所有尝试才尝试1.7_dev 并且能成功运行 + 同步数据 

> 同步了9亿多数据 4个并行 执行了11个消失


> file: '/data/software/flinkx/plugins/mysqlreader/flinkx-mysql-reader.jar' (valid JAR)
file: '/data/software/flinkx/plugins/hdfswriter/flinkx-hdfs-writer.jar' (valid JAR)
file: '/data/software/flinkx/plugins/common/flinkx-rdb.jar' (valid JAR)
这三个文件 第一台和 后面几台的确不一样
第一台是1.7_dev 后面都是1.5

**Comment by yangsishu** [comment]
插件包的每台都是要一样的

**Comment by yelijun** [comment]
之前没个节点都是 1.5的时候 我没有执行成功过。standalone的集群 我试过1.5是可以成功的，
唯一遇到的问题是 任务失败了 界面上显示 tm 都是0

我一会试下 每台机器上 都换成1.7_dev的试试


thanks
