### ISSUE TITLE
1.11_release start failed

### ISSUE THREAD

**Issue by dbsd11** [DTStack/flinkx#352]
While run `mvn clean package -DskipTests` successfuly, however when I start flinkx with such command throws ClassCastException:
     `bin/flinkx -mode local -job data-pipeline/kafka_data.json -pluginRoot syncplugins`

---
Caused by: java.lang.ClassCastException: org.apache.flink.core.io.GenericInputSplit cannot be cast to com.dtstack.flinkx.kafkabase.KafkaInputSplit
	at com.dtstack.flinkx.kafkabase.format.KafkaBaseInputFormat.openInternal(KafkaBaseInputFormat.java:99)
	at com.dtstack.flinkx.inputformat.BaseRichInputFormat.open(BaseRichInputFormat.java:171)
	at com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:124)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:213)

**Comment by dbsd11** [comment]
Use `kafkareader` instead. Now It's running online.
