### ISSUE TITLE
flinkx 本地win10不报错, 打包好放到 centos7 报错了, Log4jLoggerFactory cannot be cast to ch.qos.logback.classic.LoggerContext 具体帮忙看看 剩下的 代码 

### ISSUE THREAD

**Issue by ithjz** [DTStack/flinkx#360]
flinkx 本地win10不报错, 打包好放到 centos7 报错了, Log4jLoggerFactory cannot be cast to ch.qos.logback.classic.LoggerContext 具体帮忙看看 剩下的 代码 

Exception in thread "main" java.lang.ClassCastException: org.slf4j.impl.Log4jLoggerFactory cannot be cast to ch.q                                                                                             os.logback.classic.LoggerContext
        at com.dtstack.flinkx.launcher.Launcher.setLogLevel(Launcher.java:278)
        at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:96)
Exception in thread "main" java.lang.ClassCastException: org.slf4j.impl.Log4jLoggerFactory cannot be cast to ch.q                                                                                             os.logback.classic.LoggerContext
        at com.dtstack.flinkx.launcher.Launcher.setLogLevel(Launcher.java:278)
        at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:96)

**Comment by ithjz** [comment]
sh   flinkx  -mode local  -job  /data01/soft/1flinkx2ckrw/docs/example/c1.json    -pluginRoot syncplugins   -flinkconf flinkconf

 cat nohup.out
Exception in thread "main" java.lang.ClassCastException: org.slf4j.impl.Log4jLoggerFactory cannot be cast to ch.qos.logback.classic.LoggerContext
        at com.dtstack.flinkx.launcher.Launcher.setLogLevel(Launcher.java:278)
        at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:96)

**Comment by kanata163** [comment]
setLogLevel这个方法在新的版本中应该都被移除了，你同步一下GitHub上FlinkX的代码，然后重新编译下launcher模块
