### ISSUE TITLE
yarn是否支持yarn-cluster模式？

### ISSUE THREAD

**Issue by Nieal-Yang** [DTStack/flinkx#40]

**Comment by yangsishu** [comment]
是支持yarn-cluster 模式部署的

**Comment by yangsishu** [comment]
Now I'm doing a breakpoint continuation

**Comment by Nieal-Yang** [comment]
提交任务的命令是？

**Comment by Nieal-Yang** [comment]
eg： sh flinkx.sh -mode yarnPer -job /opt/dtstack/tmp/sqlserver_sqlserver.txt -plugin /opt/dtstack/flinkx_171plugin -flinkconf /opt/dtstack/flink-1.7.1/conf -yarnconf /opt/dtstack/hadoop/etc/hadoop -confProp {"jobmanager\.memory\.mb":1276,"taskmanager.memory.mb":1276,"taskmanager.num":2,"taskmanager.slots":2} -flinkLibJar /opt/dtstack/flink-1.7.1/lib

**Comment by ruhengChen** [comment]
支持吗? 我看到ClusterClientFactory 里面并没有支持啊?
` public static ClusterClient createClusterClient(LauncherOptions launcherOptions) throws Exception {
        String mode = launcherOptions.getMode();
        if(mode.equals(ClusterMode.standalone.name())) {
            return createStandaloneClient(launcherOptions);
        } else if(mode.equals(ClusterMode.yarn.name())) {
            return createYarnClient(launcherOptions);
        }
        throw new IllegalArgumentException("Unsupported cluster client type: ");
    }`

ClusterMode 里面只是定义了yarnPer 但是并没有用到?

**Comment by Nieal-Yang** [comment]
支持yarn-perjob这种模式提交任务的呀  不过我用的1.7这个分支

**Comment by ruhengChen** [comment]
> 支持yarn-perjob这种模式提交任务的呀 不过我用的1.7这个分支

切换到1.7可以了, 但是还是报以下错误
`Exception in thread "main" org.apache.flink.shaded.jackson2.com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'jobmanager': was expecting ('true', 'false' or 'null')
 at [Source: jobmanager\.memory\.mb:1276; line: 1, column: 11]
        at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
        at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
        at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2753)
        at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1824)
        at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:708)
        at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3847)
        at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3792)
        at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2797)
        at com.dtstack.flinkx.util.JsonUtils.jsonStrToObject(JsonUtils.java:38)
        at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:132)
`
有遇到过吗?

**Comment by ruhengChen** [comment]
> > 支持yarn-perjob这种模式提交任务的呀 不过我用的1.7这个分支
> 
> 切换到1.7可以了, 但是还是报以下错误
> `Exception in thread "main" org.apache.flink.shaded.jackson2.com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'jobmanager': was expecting ('true', 'false' or 'null') at [Source: jobmanager\.memory\.mb:1276; line: 1, column: 11] at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586) at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521) at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2753) at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1824) at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:708) at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3847) at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3792) at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2797) at com.dtstack.flinkx.util.JsonUtils.jsonStrToObject(JsonUtils.java:38) at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:132) `
> 有遇到过吗?

已解决,  是提交时 需要对{} 和 "" 都要加 \
