### ISSUE TITLE
ftp2stream 目录没有可读文件？

### ISSUE THREAD

**Issue by wushuoyouting** [DTStack/flinkx#410]
本测试环境是在阿里云上，ftp安装在asrserver001，flinkx安装在asrserver002，002服务器ftp远程001能够正常读取数据。不知道这个问题我说清楚没，不管任何答案都感谢您的回答

// asrserver002服务器ftp远程asrserver001获取文件正常
[root@asrserver002 flinkx-1.10]# ftp asrserver001 21
Connected to asrserver001 (172.26.188.13).
220 (vsFTPd 3.0.2)
Name (asrserver001:root): ftpuser
331 Please specify the password.
Password:
230 Login successful.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
227 Entering Passive Mode (172,26,188,13,88,83).
150 Here comes the directory listing.
-rwxrwxrwx    1 0        0              38 Jun 03 13:44 emp
-rwxrwxrwx    1 1000     1000           38 Jun 03 14:27 emp.csv
226 Directory send OK.
ftp> ll
?Invalid command
ftp> get emp.csv
local: emp.csv remote: emp.csv
227 Entering Passive Mode (172,26,188,13,79,51).
150 Opening BINARY mode data connection for emp.csv (38 bytes).
226 Transfer complete.
38 bytes received in 0.00116 secs (32.87 Kbytes/sec)

// 读取的emp.csv文件具有足够的权限，也归属于ftp账号ftpuser
![image](https://user-images.githubusercontent.com/34428872/120666622-517ee380-c4bf-11eb-9311-063301ea2d12.png)

//这是emp.csv
[root@asrserver001 ftpfile]# cat emp.csv 
1,wen
2,hua
3,dong
4,qiu
5,mei
6,zhen

// 报错日志
22:47:40.242 [Source: ftpreader -> Sink: streamwriter (1/1)] INFO com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction - End initialize input format state
22:47:40.248 [flink-akka.actor.default-dispatcher-2] DEBUG org.apache.flink.api.common.io.DefaultInputSplitAssigner - Assigning split com.dtstack.flinkx.inputformat.ErrorInputSplit@f1cdfcb to localhost
22:47:40.248 [flink-akka.actor.default-dispatcher-2] DEBUG org.apache.flink.runtime.jobmaster.JobMaster - Send next input split com.dtstack.flinkx.inputformat.ErrorInputSplit@f1cdfcb.
22:47:40.256 [Legacy Source Thread - Source: ftpreader -> Sink: streamwriter (1/1)] INFO com.dtstack.flinkx.ftp.reader.FtpInputFormat - configInfo : 
{
  "content": [
    {
      "reader": {
        "parameter": {
          "path": "/ftpfile/*",
          "protocol": "ftp",
          "connectMode": "PORT",
          "port": 21,
          "isFirstLineHeader": false,
          "host": "asrserver001",
          "column": [
            {
              "index": 0,
              "type": "INT",
              "key": 0
            },
            {
              "index": 1,
              "type": "STRING",
              "key": 1
            }
          ],
          "fieldDelimiter": ",",
          "encoding": "utf-8",
          "username": "ftpuser",
          "password": "******"
        },
        "name": "ftpreader"
      },
      "writer": {
        "parameter": {
          "print": true
        },
        "name": "streamwriter"
      }
    }
  ],
  "setting": {
    "speed": {
      "channel": 1
    }
  }
}
22:47:40.374 [Legacy Source Thread - Source: ftpreader -> Sink: streamwriter (1/1)] INFO com.dtstack.flinkx.ftp.reader.FtpInputFormat - subtask input close finished
22:47:40.375 [Legacy Source Thread - Source: ftpreader -> Sink: streamwriter (1/1)] ERROR com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction - DtInputFormatSourceFunction error, info: java.lang.RuntimeException: java.lang.RuntimeException: There are no readable files  in directory /ftpfile/emp.csv
	at com.dtstack.flinkx.ftp.reader.FtpInputFormat.createInputSplitsInternal(FtpInputFormat.java:79)
	at com.dtstack.flinkx.inputformat.BaseRichInputFormat.createInputSplits(BaseRichInputFormat.java:128)
	at org.apache.flink.runtime.executiongraph.ExecutionJobVertex.<init>(ExecutionJobVertex.java:257)
	at org.apache.flink.runtime.executiongraph.ExecutionGraph.attachJobGraph(ExecutionGraph.java:807)
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:228)
	at org.apache.flink.runtime.scheduler.SchedulerBase.createExecutionGraph(SchedulerBase.java:256)
	at org.apache.flink.runtime.scheduler.SchedulerBase.createAndRestoreExecutionGraph(SchedulerBase.java:228)
	at org.apache.flink.runtime.scheduler.SchedulerBase.<init>(SchedulerBase.java:216)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.<init>(DefaultScheduler.java:120)
	at org.apache.flink.runtime.scheduler.DefaultSchedulerFactory.createInstance(DefaultSchedulerFactory.java:105)
	at org.apache.flink.runtime.jobmaster.JobMaster.createScheduler(JobMaster.java:278)
	at org.apache.flink.runtime.jobmaster.JobMaster.<init>(JobMaster.java:266)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:98)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:40)
	at org.apache.flink.runtime.jobmaster.JobManagerRunnerImpl.<init>(JobManagerRunnerImpl.java:146)
	at org.apache.flink.runtime.dispatcher.DefaultJobManagerRunnerFactory.createJobManagerRunner(DefaultJobManagerRunnerFactory.java:84)
	at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$createJobManagerRunner$6(Dispatcher.java:381)
	at org.apache.flink.util.function.CheckedSupplier.lambda$unchecked$0(CheckedSupplier.java:34)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

	at com.dtstack.flinkx.inputformat.BaseRichInputFormat.checkIfCreateSplitFailed(BaseRichInputFormat.java:196)
	at com.dtstack.flinkx.inputformat.BaseRichInputFormat.open(BaseRichInputFormat.java:156)
	at com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:124)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:200)

java.lang.RuntimeException: java.lang.RuntimeException: There are no readable files  in directory /ftpfile/emp.csv
	at com.dtstack.flinkx.ftp.reader.FtpInputFormat.createInputSplitsInternal(FtpInputFormat.java:79)
	at com.dtstack.flinkx.inputformat.BaseRichInputFormat.createInputSplits(BaseRichInputFormat.java:128)
	at org.apache.flink.runtime.executiongraph.ExecutionJobVertex.<init>(ExecutionJobVertex.java:257)
	at org.apache.flink.runtime.executiongraph.ExecutionGraph.attachJobGraph(ExecutionGraph.java:807)
	at org.apache.flink.runtime.executiongraph.ExecutionGraphBuilder.buildGraph(ExecutionGraphBuilder.java:228)
	at org.apache.flink.runtime.scheduler.SchedulerBase.createExecutionGraph(SchedulerBase.java:256)
	at org.apache.flink.runtime.scheduler.SchedulerBase.createAndRestoreExecutionGraph(SchedulerBase.java:228)
	at org.apache.flink.runtime.scheduler.SchedulerBase.<init>(SchedulerBase.java:216)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.<init>(DefaultScheduler.java:120)
	at org.apache.flink.runtime.scheduler.DefaultSchedulerFactory.createInstance(DefaultSchedulerFactory.java:105)
	at org.apache.flink.runtime.jobmaster.JobMaster.createScheduler(JobMaster.java:278)
	at org.apache.flink.runtime.jobmaster.JobMaster.<init>(JobMaster.java:266)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:98)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:40)
	at org.apache.flink.runtime.jobmaster.JobManagerRunnerImpl.<init>(JobManagerRunnerImpl.java:146)
	at org.apache.flink.runtime.dispatcher.DefaultJobManagerRunnerFactory.createJobManagerRunner(DefaultJobManagerRunnerFactory.java:84)
	at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$createJobManagerRunner$6(Dispatcher.java:381)
	at org.apache.flink.util.function.CheckedSupplier.lambda$unchecked$0(CheckedSupplier.java:34)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

	at com.dtstack.flinkx.inputformat.BaseRichInputFormat.checkIfCreateSplitFailed(BaseRichInputFormat.java:196)
	at com.dtstack.flinkx.inputformat.BaseRichInputFormat.open(BaseRichInputFormat.java:156)
	at com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:124)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:200)
22:47:40.377 [Source: ftpreader -> Sink: streamwriter (1/1)] INFO com.dtstack.flinkx.stream.writer.StreamOutputFormat - subtask[0}] close()
22:47:40.612 [Checkpoint Timer] INFO org.apache.flink.runtime.checkpoint.CheckpointCoordinator - Triggering checkpoint 1 @ 1622731660608 for job 3a3c641050a9fdfcba5c4c698986d253.
22:47:40.613 [flink-akka.actor.default-dispatcher-3] DEBUG org.apache.flink.runtime.taskexecutor.TaskExecutor - Trigger checkpoint 1@1622731660608 for 7f8b3e02db36d3012ceba30a7dc35c87.
22:47:49.537 [flink-akka.actor.default-dispatcher-3] DEBUG org.apache.flink.runtime.resourcemanager.StandaloneResourceManager - Trigger heartbeat request.
22:47:49.537 [flink-akka.actor.default-dispatcher-3] DEBUG org.apache.flink.runtime.resourcemanager.StandaloneResourceManager - Trigger heartbeat request.
22:47:49.538 [flink-akka.actor.default-dispatcher-3] DEBUG org.apache.flink.runtime.taskexecutor.TaskExecutor - Received heartbeat request from 8e708f51110816a9a5b6ee3e4c58ba35.
22:47:49.538 [flink-akka.actor.default-dispatcher-4] DEBUG org.apache.flink.runtime.jobmaster.JobMaster - Received heartbeat request from 8e708f51110816a9a5b6ee3e4c58ba35.
22:47:49.539 [flink-akka.actor.default-dispatcher-4] DEBUG org.apache.flink.runtime.resourcemanager.StandaloneResourceManager - Received heartbeat from 69b961bcf7a8635b39edeba43293be3f.
22:47:49.539 [flink-akka.actor.default-dispatcher-4] DEBUG org.apache.flink.runtime.resourcemanager.StandaloneResourceManager - Received heartbeat from ce455ded-77a7-4300-a0f3-7f541457b4a6.
22:47:49.539 [flink-akka.actor.default-dispatcher-4] DEBUG org.apache.flink.runtime.resourcemanager.slotmanager.SlotManagerImpl - Received slot report from instance 4a3a82fd9ab56381191d828aebb5dbcf: SlotReport{slotsStatus=[SlotStatus{slotID=ce455ded-77a7-4300-a0f3-7f541457b4a6_0, resourceProfile=ResourceProfile{managedMemory=512.000mb (536870912 bytes), networkMemory=64.000mb (67108864 bytes)}, allocationID=6fddf32eeddf4f6e6a0afc1a7f22dcb0, jobID=3a3c641050a9fdfcba5c4c698986d253}]}.
22:47:50.117 [flink-akka.actor.default-dispatcher-4] DEBUG org.apache.flink.runtime.jobmaster.JobMaster - Trigger heartbeat request.
22:47:50.118 [flink-akka.actor.default-dispatcher-3] DEBUG org.apache.flink.runtime.taskexecutor.TaskExecutor - Received heartbeat request from 69b961bcf7a8635b39edeba43293be3f.
22:47:50.128 [flink-akka.actor.default-dispatcher-3] DEBUG org.apache.flink.runtime.jobmaster.JobMaster - Received heartbeat from ce455ded-77a7-4300-a0f3-7f541457b4a6.
22:47:59.557 [flink-akka.actor.default-dispatcher-4] DEBUG org.apache.flink.runtime.resourcemanager.StandaloneResourceManager - Trigger heartbeat request.
22:47:59.557 [flink-akka.actor.default-dispatcher-4] DEBUG org.apache.flink.runtime.resourcemanager.StandaloneResourceManager - Trigger heartbeat request.
22:47:59.557 [flink-akka.actor.default-dispatcher-5] DEBUG org.apache.flink.runtime.taskexecutor.TaskExecutor - Received heartbeat request from 8e708f51110816a9a5b6ee3e4c58ba35.
22:47:59.557 [flink-akka.actor.default-dispatcher-4] DEBUG org.apache.flink.runtime.jobmaster.JobMaster - Received heartbeat request from 8e708f51110816a9a5b6ee3e4c58ba35.
22:47:59.558 [flink-akka.actor.default-dispatcher-4] DEBUG org.apache.flink.runtime.resourcemanager.StandaloneResourceManager - Received heartbeat from 69b961bcf7a8635b39edeba43293be3f.
22:47:59.558 [flink-akka.actor.default-dispatcher-4] DEBUG org.apache.flink.runtime.resourcemanager.StandaloneResourceManager - Received heartbeat from ce455ded-77a7-4300-a0f3-7f541457b4a6.
22:47:59.558 [flink-akka.actor.default-dispatcher-4] DEBUG org.apache.flink.runtime.resourcemanager.slotmanager.SlotManagerImpl - Received slot report from instance 4a3a82fd9ab56381191d828aebb5dbcf: SlotReport{slotsStatus=[SlotStatus{slotID=ce455ded-77a7-4300-a0f3-7f541457b4a6_0, resourceProfile=ResourceProfile{managedMemory=512.000mb (536870912 bytes), networkMemory=64.000mb (67108864 bytes)}, allocationID=6fddf32eeddf4f6e6a0afc1a7f22dcb0, jobID=3a3c641050a9fdfcba5c4c698986d253}]}.
22:48:00.137 [flink-akka.actor.default-dispatcher-4] DEBUG org.apache.flink.runtime.jobmaster.JobMaster - Trigger heartbeat request.
22:48:00.137 [flink-akka.actor.default-dispatcher-5] DEBUG org.apache.flink.runtime.taskexecutor.TaskExecutor - Received heartbeat request from 69b961bcf7a8635b39edeba43293be3f.
22:48:00.138 [flink-akka.actor.default-dispatcher-4] DEBUG org.apache.flink.runtime.jobmaster.JobMaster - Received heartbeat from ce455ded-77a7-4300-a0f3-7f541457b4a6.
22:48:00.377 [Source: ftpreader -> Sink: streamwriter (1/1)] INFO com.dtstack.flinkx.stream.writer.StreamOutputFormat - subtask[0}] close() finished

**Comment by wushuoyouting** [comment]
客户端的“/”==>服务端的"/ftpfile"，是客户端路径写错了

**Comment by zoudaokoulife** [comment]
使用问题
