### ISSUE TITLE
oraclereader will add double quotation to each colum which will cause ORA-00904 error

### ISSUE THREAD

**Issue by lordk911** [DTStack/flinkx#416]
Caused by: java.sql.SQLSyntaxErrorException: ORA-00904: "early_type": invalid identifier

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:213)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:37)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:733)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:904)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1082)
	at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1276)
	at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:366)
	at com.dtstack.flinkx.rdb.inputformat.JdbcInputFormat.executeQuery(JdbcInputFormat.java:788)
	at com.dtstack.flinkx.rdb.inputformat.JdbcInputFormat.openInternal(JdbcInputFormat.java:149)
	... 5 more
Caused by: Error : 904, Position : 761, Sql = SELECT "row_wid","date_wid","order_id","sales_id","branch_wid","customer_wid","prod_wid","service_num","line_id","node_num","start_dt","end_dt","add_node_num","lock_date","split_amt_pkg","split_amt","split_amt_received","data_source","buy_type","add_flag","month_deal_flag","day_deal_flag","created_date","last_modified_date","load_batch","integration_id","split_amt_returned","split_amt_owed","new_prod_type","fix_price","trans_type","agree_wid","normal_agree_id","inv_dt","new_fix_price","new_total_price","max_end_dt","sq_mons","kn_flag","many_year_split_amt","many_year_flag","freight_rate","installation_costs","standard_costs","off_standard_costs","tripartite_cost","installation_rate","standard_costs_price","freight_costs","general_type","package_type","early_type" FROM "PRO_DW"."DW_SALES_AMT_FCT" WHERE 1=1  AND date_wid >= 20170101 and date_wid <= 20171231, OriginalSql = SELECT "row_wid","date_wid","order_id","sales_id","branch_wid","customer_wid","prod_wid","service_num","line_id","node_num","start_dt","end_dt","add_node_num","lock_date","split_amt_pkg","split_amt","split_amt_received","data_source","buy_type","add_flag","month_deal_flag","day_deal_flag","created_date","last_modified_date","load_batch","integration_id","split_amt_returned","split_amt_owed","new_prod_type","fix_price","trans_type","agree_wid","normal_agree_id","inv_dt","new_fix_price","new_total_price","max_end_dt","sq_mons","kn_flag","many_year_split_amt","many_year_flag","freight_rate","installation_costs","standard_costs","off_standard_costs","tripartite_cost","installation_rate","standard_costs_price","freight_costs","general_type","package_type","early_type" FROM "PRO_DW"."DW_SALES_AMT_FCT" WHERE 1=1  AND date_wid >= 20170101 and date_wid <= 20171231, Error Msg = ORA-00904: "early_type": invalid identifier

**Comment by lordk911** [comment]
SELECT "row_wid" FROM PRO_DW.DW_SALES_AMT_FCT where rownum<2    will cause  ORA-00904;

SELECT row_wid FROM PRO_DW.DW_SALES_AMT_FCT where rownum<2      is ok.

**Comment by kyo-tom** [comment]
you can try replace early_type as EARLY_TYPE in script json

**Comment by lordk911** [comment]
> you can try replace early_type as EARLY_TYPE in script json

thanks,it works for me.
