### ISSUE TITLE
各位运行有啥问题吗，我这错误解决不了啊，实在不知道哪出问题了

### ISSUE THREAD

**Issue by Horrypotter** [DTStack/flinkx#45]
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: Could not submit job 58e0b47031e88ada6c51bc5f36b9b717.
        at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:247)
        at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:464)
        at org.apache.flink.client.program.DetachedEnvironment.finalizeExecute(DetachedEnvironment.java:77)
        at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:410)
        at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:100)
Caused by: org.apache.flink.runtime.client.JobSubmissionException: Failed to submit JobGraph.
        at org.apache.flink.client.program.rest.RestClusterClient.lambda$submitJob$8(RestClusterClient.java:370)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at org.apache.flink.runtime.concurrent.FutureUtils.lambda$retryOperationWithDelay$5(FutureUtils.java:213)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:929)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.CompletionException: org.apache.flink.runtime.concurrent.FutureUtils$RetryException: Could not complete the operation. Exception is not retryable.
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
        at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
        at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899)
        ... 12 more
Caused by: org.apache.flink.runtime.concurrent.FutureUtils$RetryException: Could not complete the operation. Exception is not retryable.
        ... 10 more
Caused by: java.util.concurrent.CompletionException: org.apache.flink.runtime.rest.util.RestClientException: [Job submission failed.]
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
        at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:953)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
        ... 4 more
Caused by: org.apache.flink.runtime.rest.util.RestClientException: [Job submission failed.]
        at org.apache.flink.runtime.rest.RestClient.parseResponse(RestClient.java:308)
        at org.apache.flink.runtime.rest.RestClient.lambda$submitRequest$3(RestClient.java:292)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
        ... 5 more

**Comment by Horrypotter** [comment]
flink是下载的官方的，start-cluster.sh启动的，flinkx以standalone启动的，想测试从mysql到postgresql的数据抽取！结果老是报上面的错，

**Comment by Horrypotter** [comment]
flinkx 用local模式没问题，就是慢

**Comment by yangsishu** [comment]
flink什么版本

**Comment by Horrypotter** [comment]
flinkx：V1.51分支
flink:flink-1.7.2-bin-hadoop28-scala_2.12.tar和阿里的blink（基于flink1.5.1改造的）
flink这两个版本都在local上没问题，standalone上报错

**Comment by yangsishu** [comment]
blink没测试过，flinkx：V1.51对应flink1.5版本，flinkxv1.7对应flink1.7；

**Comment by yangsishu** [comment]
flinkx的版本要和flink的版本对应
