### ISSUE TITLE
java.lang.ClassCastException:  GenericRowData cannot be cast to ColumnRowData

### ISSUE THREAD

**Issue by geosmart** [DTStack/flinkx#496]
version-flinkx 1.12
when use hdfs sync to mysql ,throw this exception
```java
java.lang.ClassCastException: org.apache.flink.table.data.GenericRowData cannot be cast to com.dtstack.flinkx.element.ColumnRowData
	at com.dtstack.flinkx.connector.jdbc.converter.JdbcColumnConverter.lambda$wrapIntoNullableExternalConverter$421947be$1(JdbcColumnConverter.java:75)
	at com.dtstack.flinkx.connector.jdbc.converter.JdbcColumnConverter.toExternal(JdbcColumnConverter.java:107)
	at com.dtstack.flinkx.connector.jdbc.converter.JdbcColumnConverter.toExternal(JdbcColumnConverter.java:50)
	at com.dtstack.flinkx.connector.jdbc.sink.JdbcOutputFormat.writeSingleRecordInternal(JdbcOutputFormat.java:174)
	at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeSingleRecord(BaseRichOutputFormat.java:465)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeRecordInternal(BaseRichOutputFormat.java:485)
	at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeRecord(BaseRichOutputFormat.java:239)
	at com.dtstack.flinkx.sink.format.BaseRichOutputFormat.writeRecord(BaseRichOutputFormat.java:81)
	at com.dtstack.flinkx.sink.DtOutputFormatSinkFunction.invoke(DtOutputFormatSinkFunction.java:117)
	at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:54)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:71)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:46)
	at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:26)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:50)
	at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:28)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollect(StreamSourceContexts.java:317)
	at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collect(StreamSourceContexts.java:411)
	at com.dtstack.flinkx.source.DtInputFormatSourceFunction.run(DtInputFormatSourceFunction.java:135)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:66)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:263)
```

**Comment by deadwind4** [comment]
拉取最新的master分支再试下

**Comment by geosmart** [comment]
the `1.12_beta` has this bug
the `master` branch is working

**Comment by libailin** [comment]
1.12_beta patch from my changes :
![image](https://user-images.githubusercontent.com/3014381/137890697-7408d9b7-7176-469c-a659-cda9855c8018.png)
