### ISSUE TITLE
写入HDFS连接超时

### ISSUE THREAD

**Issue by zhihui-ge** [DTStack/flinkx#6]
1.集群式HDP版本的
2.端口是通的
telnet 192.168.112.47 8020
Trying 192.168.112.47...
Connected to 192.168.112.47.
Escape character is '^]'.

3.异常信息
14:52:51.595 [flink-akka.actor.default-dispatcher-9] DEBUG akka.event.EventStream - shutting down: StandardOutLogger started
Exception in thread "main" org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$6.apply$mcV$sp(JobManager.scala:897)
	at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$6.apply(JobManager.scala:840)
	at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$6.apply(JobManager.scala:840)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.net.ConnectException: Call From hadoop1.test.yunwei.puppet.dh/192.168.112.47 to DHTestCluster:8020 failed on connection exception: java.net.ConnectException: Connection timed out; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:783)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:730)
	at org.apache.hadoop.ipc.Client.call(Client.java:1414)
	at org.apache.hadoop.ipc.Client.call(Client.java:1363)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:206)
	at com.sun.proxy.$Proxy13.getFileInfo(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:190)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:103)
	at com.sun.proxy.$Proxy13.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:699)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1762)
	at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1124)
	at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1120)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1120)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1398)
	at com.dtstack.flinkx.hdfs.writer.HdfsOutputFormat.openInternal(HdfsOutputFormat.java:139)
	at com.dtstack.flinkx.outputformat.RichOutputFormat.open(RichOutputFormat.java:189)
	at org.apache.flink.streaming.api.functions.sink.OutputFormatSinkFunction.open(OutputFormatSinkFunction.java:61)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:393)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:254)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:718)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection timed out
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:529)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:493)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:604)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:699)
	at org.apache.hadoop.ipc.Client$Connection.access$2800(Client.java:367)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1462)
	at org.apache.hadoop.ipc.Client.call(Client.java:1381)
	... 27 more

**Comment by yangsishu** [comment]
你的hadoop是什么版本

**Comment by yangsishu** [comment]
首先你要确认下你的hadoop 搭建是没问题，你可以写个demo 程序看写入hadoop有没有问题

**Comment by zhihui-ge** [comment]
hadoop是2.7的，hadoop应该没有问题，flume可以写入数据到hdfs的，之前试过datax也是可以写入数据的

**Comment by yangsishu** [comment]
"dfs.client.failover.proxy.DHTestCluster.ns1": "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider" 这个配置错了吧应该是

"dfs.client.failover.proxy.DHTestCluster": "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider"

**Comment by yangsishu** [comment]
com.dtstack.flinkx.hdfs.writer.HdfsOutputFormat.openInternal(HdfsOutputFormat.java:139) 是在这行访问hadoop报错了，这是初始化的动作

**Comment by yangsishu** [comment]
应该还是配置的问题

**Comment by yangsishu** [comment]
com.dtstack.flinkx.hdfs.writer.HdfsOutputFormat.openInternal 在这个方法设置个断点，debug下

**Comment by yangsishu** [comment]
"dfs.namenode.rpc-address.DHTestCluster.nn1": "hadoop1.test.yunwei.puppet.dh:8020"  端口应该是9000吧

**Comment by zhihui-ge** [comment]
端口是没有问题，使用ambari搭建的集群，配置的端口是8020

**Comment by yangsishu** [comment]
我们的框架读写都是9000端口，你改成9000试下

**Comment by yangsishu** [comment]
你能把hdfs-site.xml 的配置贴出来吗

**Comment by zhihui-ge** [comment]
粘贴了部分，job.json文件改成9000端口，还是会去连接8020端口的

 <property>
      <name>dfs.namenode.rpc-address.DHTestCluster.nn1</name>
      <value>hadoop1.test.yunwei.puppet.dh:8020</value>
    </property>
    
    <property>
      <name>dfs.namenode.rpc-address.DHTestCluster.nn2</name>
      <value>hadoop2.test.yunwei.puppet.dh:8020</value>
    </property>

**Comment by zhihui-ge** [comment]
粘贴了部分配置文件，job.json文件改成了9000端口，还是会去连接8020端口
` <property>
      <name>dfs.namenode.rpc-address.DHTestCluster.nn1</name>
      <value>hadoop1.test.yunwei.puppet.dh:8020</value>
    </property>
    
    <property>
      <name>dfs.namenode.rpc-address.DHTestCluster.nn2</name>
      <value>hadoop2.test.yunwei.puppet.dh:8020</value>
    </property>`

**Comment by zhihui-ge** [comment]
![image](https://user-images.githubusercontent.com/17016370/42356640-30b6d7b6-8106-11e8-8df2-0ca8e494257a.png)
![image](https://user-images.githubusercontent.com/17016370/42356647-383f21be-8106-11e8-9079-daa032c3d4f1.png)

**Comment by zhihui-ge** [comment]
可以了，有个配置写错了，不好意思耽误你的时间了
