### ISSUE TITLE
编译flinkx core报错Failed to read artifact descriptor for com.google.errorprone:javac-shaded:jar:9

### ISSUE THREAD

**Issue by zhanghui-china** [DTStack/flinkx#609]
## General Question

[INFO] -------------------< com.dtstack.flinkx:flinkx-core >-------------------
[INFO] Building FlinkX : Core 1.12-SNAPSHOT                              [2/51]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- spotless-maven-plugin:2.4.2:check (spotless-check) @ flinkx-core ---
Downloading from alimaven: http://maven.aliyun.com/nexus/content/groups/public/com/google/errorprone/javac-shaded/9+181-r4173-1/javac-shaded-9+181-r4173-1.pom
Downloading from alimaven: http://maven.aliyun.com/nexus/content/groups/public/com/google/errorprone/javac-shaded/9+181-r4173-1/javac-shaded-9+181-r4173-1.jar
二月 19, 2022 8:56:09 下午 com.diffplug.spotless.FormatExceptionPolicyLegacy error
严重: Step 'google-java-format' found problem in 'src\main\java\com\dtstack\flinkx\cdc\CdcConf.java':
Unable to resolve dependencies
com.diffplug.spotless.maven.ArtifactResolutionException: Unable to resolve dependencies
        at com.diffplug.spotless.maven.ArtifactResolver.resolveDependencies(ArtifactResolver.java:88)
        at com.diffplug.spotless.maven.ArtifactResolver.resolve(ArtifactResolver.java:74)
        at com.diffplug.spotless.JarState.provisionWithTransitives(JarState.java:68)
        at com.diffplug.spotless.JarState.from(JarState.java:57)
        at com.diffplug.spotless.JarState.from(JarState.java:52)
        at com.diffplug.spotless.java.GoogleJavaFormatStep$State.<init>(GoogleJavaFormatStep.java:123)
        at com.diffplug.spotless.java.GoogleJavaFormatStep.lambda$create$0(GoogleJavaFormatStep.java:75)
        at com.diffplug.spotless.FormatterStepImpl.calculateState(FormatterStepImpl.java:56)
        at com.diffplug.spotless.LazyForwardingEquality.state(LazyForwardingEquality.java:56)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:76)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:201)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:188)
        at com.diffplug.spotless.maven.SpotlessCheckMojo.process(SpotlessCheckMojo.java:52)
        at com.diffplug.spotless.maven.AbstractSpotlessMojo.execute(AbstractSpotlessMojo.java:146)
        at com.diffplug.spotless.maven.AbstractSpotlessMojo.execute(AbstractSpotlessMojo.java:137)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at com.google.googlejavaformat:google-java-format:jar:1.7 -> com.google.errorprone:javac-shaded:jar:9+181-r4173-1
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:353)
        at com.diffplug.spotless.maven.ArtifactResolver.resolveDependencies(ArtifactResolver.java:86)
        ... 37 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at com.google.googlejavaformat:google-java-format:jar:1.7 -> com.google.errorprone:javac-shaded:jar:9+181-r4173-1
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:288)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309)
        ... 38 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for com.google.errorprone:javac-shaded:jar:9+181-r4173-1
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:259)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:175)
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:538)
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:523)
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:410)
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:362)
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:349)
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:506)
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:458)
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:362)
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:349)
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
        ... 39 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact com.google.errorprone:javac-shaded:pom:9+181-r4173-1 from/to alimaven (http://maven.aliyun.com/nexus/content/groups/public/): authorization failed for http://maven.aliyun.com/nexus/content/groups/public/com/google/errorprone/javac-shaded/9+181-r4173-1/javac-shaded-9+181-r4173-1.pom, status: 403 Forbidden
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:425)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:244)
        ... 50 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact com.google.errorprone:javac-shaded:pom:9+181-r4173-1 from/to alimaven (http://maven.aliyun.com/nexus/content/groups/public/): authorization failed for http://maven.aliyun.com/nexus/content/groups/public/com/google/errorprone/javac-shaded/9+181-r4173-1/javac-shaded-9+181-r4173-1.pom, status: 403 Forbidden
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:628)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:514)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402)
        ... 53 more
Caused by: org.apache.maven.wagon.authorization.AuthorizationException: authorization failed for http://maven.aliyun.com/nexus/content/groups/public/com/google/errorprone/javac-shaded/9+181-r4173-1/javac-shaded-9+181-r4173-1.pom, status: 403 Forbidden
        at org.apache.maven.wagon.providers.http.wagon.shared.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1184)
        at org.apache.maven.wagon.providers.http.wagon.shared.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1140)
        at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:126)
        at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
        at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
        at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:546)
        at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:430)
        at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:407)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:457)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
        ... 58 more

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for FlinkX 1.12-SNAPSHOT:
[INFO]
[INFO] FlinkX ............................................. SUCCESS [  3.344 s]
[INFO] FlinkX : Core ...................................... FAILURE [  3.842 s]
[INFO] FlinkX : Connectors : .............................. SKIPPED
[INFO] FlinkX : Connectors : Stream ....................... SKIPPED
[INFO] FlinkX : Connectors : Kafka ........................ SKIPPED
[INFO] FlinkX : Connectors : EMQX ......................... SKIPPED
[INFO] FlinkX : Connectors : JDBC ......................... SKIPPED
[INFO] FlinkX : Connectors : MySQL ........................ SKIPPED
[INFO] FlinkX : Connectors : Oracle ....................... SKIPPED
[INFO] FlinkX : Connectors : SqlServer .................... SKIPPED
[INFO] FlinkX : Connectors : DB2 .......................... SKIPPED
[INFO] FlinkX : Connectors : Postgresql ................... SKIPPED
[INFO] FlinkX : Connectors : GBase ........................ SKIPPED
[INFO] FlinkX : Connectors : Kingbase ..................... SKIPPED
[INFO] FlinkX : Connectors : Greenplum .................... SKIPPED
[INFO] FlinkX : Connectors : Dm ........................... SKIPPED
[INFO] FlinkX : Connectors : ClickHouse ................... SKIPPED
[INFO] FlinkX : Connectors : SAP HANA ..................... SKIPPED
[INFO] FlinkX : Connectors : Doris ........................ SKIPPED
[INFO] FlinkX : Connectors : File ......................... SKIPPED
[INFO] FlinkX : Connectors : Filesystem ................... SKIPPED
[INFO] FlinkX : Connectors : Ftp .......................... SKIPPED
[INFO] FlinkX : Connectors : HDFS ......................... SKIPPED
[INFO] FlinkX : Connectors : Hive ......................... SKIPPED
[INFO] Flink : Connectors : HBase base .................... SKIPPED
[INFO] Flink : Connectors : HBase1.4 ...................... SKIPPED
[INFO] FlinkX : Connectors : ElasticSearch base ........... SKIPPED
[INFO] FlinkX : Connectors : ElasticSearch7 ............... SKIPPED
[INFO] FlinkX : Connectors : Redis ........................ SKIPPED
[INFO] FlinkX : Connectors : MongoDB ...................... SKIPPED
[INFO] FlinkX : Connectors : Solr ......................... SKIPPED
[INFO] FlinkX : Connectors : Kudu ......................... SKIPPED
[INFO] FlinkX : Connectors : Binlog ....................... SKIPPED
[INFO] FlinkX : Connectors : Oracle LogMiner .............. SKIPPED
[INFO] FlinkX : Connectors : SqlServer CDC ................ SKIPPED
[INFO] FlinkX : Connectors : PGWal ........................ SKIPPED
[INFO] FlinkX : Connectors : Http ......................... SKIPPED
[INFO] FlinkX : Connectors : Socket ....................... SKIPPED
[INFO] FlinkX : Clients ................................... SKIPPED
[INFO] FlinkX : Formats : ................................. SKIPPED
[INFO] FlinkX : Docker .................................... SKIPPED
[INFO] FlinkX : Metrics : ................................. SKIPPED
[INFO] FlinkX : Metrics : Rdb ............................. SKIPPED
[INFO] FlinkX : Metrics : Prometheus ...................... SKIPPED
[INFO] FlinkX : Metrics : MYSQL ........................... SKIPPED
[INFO] FlinkX : Dirty ..................................... SKIPPED
[INFO] FlinkX : Dirty : Mysql ............................. SKIPPED
[INFO] FlinkX : Dirty : Log ............................... SKIPPED
[INFO] FlinkX : Restore ................................... SKIPPED
[INFO] FlinkX : Restore : Common .......................... SKIPPED
[INFO] FlinkX : Restore : MySQL ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.924 s
[INFO] Finished at: 2022-02-19T20:56:09+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.4.2:check (spotless-check) on project flinkx-core: Execution spotless-check of goal com.diffplug.spotless:spotless-maven-plugin:2.4.2:check failed: Unable to resolve dependencies: Failed to collect dependencies at com.google.googlejavaformat:google-java-format:jar:1.7 -> com.google.errorprone:javac-shaded:jar:9+181-r4173-1: Failed to read artifact descriptor for com.google.errorprone:javac-shaded:jar:9+181-r4173-1: Could not transfer artifact com.google.errorprone:javac-shaded:pom:9+181-r4173-1 from/to alimaven (http://maven.aliyun.com/nexus/content/groups/public/): authorization failed for http://maven.aliyun.com/nexus/content/groups/public/com/google/errorprone/javac-shaded/9+181-r4173-1/javac-shaded-9+181-r4173-1.pom, status: 403 Forbidden -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :flinkx-core

E:\开源中间件\flinkx\flinkx>

**Comment by xinuonuo** [comment]
一样的问题

**Comment by libailin** [comment]
https://repo1.maven.org/maven2/com/google/errorprone/javac-shaded/9+181-r4173-1/javac-shaded-9+181-r4173-1.jar

从上面这个地址下载javac-shaded-9+181-r4173-1.jar， 临时放到 chunjun根目录下的jars目录里。
然后在源码根目录执行mvn安装依赖包，

```
mvn install:install-file -DgroupId=com.google.errorprone -DartifactId=javac-shaded -Dversion=9+181-r4173-1 -Dpackaging=jar -Dfile=./jars/javac-shaded-9+181-r4173-1.jar
```

可以浏览仓库地址：
https://mvnrepository.com/artifact/com.google.errorprone/javac-shaded/9+181-r4173-1

以上方案亲自有效，版本是：
683e800c8bbf007036bf38b8b90a1921d19028fd，3ff2fbe1ff83681adb99ea2453ad45e5c562f29f
