### ISSUE TITLE
Flink1.7提交任务报超时异常，麻烦老师协助下，谢谢！

### ISSUE THREAD

**Issue by jihr** [DTStack/flinkx#78]
22:57:28.350 [main] DEBUG org.apache.flink.streaming.api.graph.StreamGraphGenerator - Transforming SinkTransformation{id=3, name='mysqlwriter', outputType=GenericType<java.lang.Object>, parallelism=3}
22:57:28.350 [main] DEBUG org.apache.flink.streaming.api.graph.StreamGraphGenerator - Transforming PartitionTransformation{id=2, name='Partition', outputType=GenericType<org.apache.flink.types.Row>, parallelism=3}
22:57:28.351 [main] DEBUG org.apache.flink.streaming.api.graph.StreamGraphGenerator - Transforming SourceTransformation{id=1, name='mysqlreader', outputType=GenericType<org.apache.flink.types.Row>, parallelism=3}
22:57:28.358 [main] DEBUG org.apache.flink.streaming.api.graph.StreamGraph - Vertex: 1
22:57:28.363 [main] DEBUG org.apache.flink.streaming.api.graph.StreamGraph - Vertex: 3
22:57:28.375 [main] DEBUG org.apache.flink.streaming.api.graph.StreamGraphHasherV2 - Generated hash 'bc764cd8ddf7a0cff126f51c16239658' for node 'Source: mysqlreader-1' {id: 1, parallelism: 3, user function: org.apache.flink.streaming.api.functions.source.InputFormatSourceFunction}
22:57:28.375 [main] DEBUG org.apache.flink.streaming.api.graph.StreamGraphHasherV2 - Generated hash '0a448493b4782967b150582570326227' for node 'Sink: mysqlwriter-3' {id: 3, parallelism: 3, user function: org.apache.flink.streaming.api.functions.sink.OutputFormatSinkFunction}
22:57:28.376 [main] DEBUG org.apache.flink.streaming.api.graph.StreamingJobGraphGenerator - Parallelism set: 3 for 3
22:57:28.394 [main] DEBUG org.apache.flink.streaming.api.graph.StreamingJobGraphGenerator - Parallelism set: 3 for 1
22:57:28.401 [main] DEBUG org.apache.flink.streaming.api.graph.StreamingJobGraphGenerator - CONNECTED: RebalancePartitioner - 1 -> 3
22:57:28.409 [main] INFO org.apache.flink.client.program.rest.RestClusterClient - Submitting job b5e885070c58e00c9874c691955f9aba (detached: false).
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: Could not retrieve the execution result. (JobID: b5e885070c58e00c9874c691955f9aba)
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:261)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:487)
	at org.apache.flink.streaming.api.environment.StreamContextEnvironment.execute(StreamContextEnvironment.java:66)
	at com.dtstack.flinkx.Main.main(Main.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:529)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:421)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:427)
	at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:111)
Caused by: org.apache.flink.runtime.client.JobSubmissionException: Failed to submit JobGraph.
	at org.apache.flink.client.program.rest.RestClusterClient.lambda$submitJob$8(RestClusterClient.java:380)
	at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:870)
	at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1595)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException
	at org.apache.flink.runtime.concurrent.FutureUtils$Timeout.run(FutureUtils.java:795)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 more

**Comment by yangsishu** [comment]
用flink1.8吧，1.7不维护了
