### ISSUE TITLE
yarn模式不能正常运行，报ClassNotFoundException

### ISSUE THREAD

**Issue by zhihui-ge** [DTStack/flinkx#8]
local模式运行没有问题，yarn模式不能正常运行
15:43:13.626 [main] INFO org.apache.flink.yarn.YarnClusterClient - Starting program in interactive mode
15:43:13.667 [main] INFO com.dtstack.flinkx.loader.DTClassLoader - urls=[file:/data/tmp/xxxxx/flinkx/plugins/common/flinkx-rdb.jar, file:/data/tmp/xxxxx/flinkx/plugins/mysqlreader/flinkx-mysql-reader.jar]
Exception in thread "main" org.apache.flink.client.program.ProgramInvocationException: The main method caused an error.
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:542)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:417)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:396)
	at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:101)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.dtstack.flinkx.mysql.reader.MysqlReader
	at com.dtstack.flinkx.plugin.PluginLoader.getPluginClass(PluginLoader.java:104)
	at com.dtstack.flinkx.reader.DataReaderFactory.getDataReader(DataReaderFactory.java:44)
	at com.dtstack.flinkx.Main.main(Main.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:525)
	... 3 more
Caused by: java.lang.ClassNotFoundException: com.dtstack.flinkx.mysql.reader.MysqlReader
	at com.dtstack.flinkx.loader.DTClassLoader.loadClass(DTClassLoader.java:100)
	at com.dtstack.flinkx.loader.DTClassLoader.loadClass(DTClassLoader.java:65)
	at com.dtstack.flinkx.plugin.PluginLoader.getPluginClass(PluginLoader.java:102)
	... 10 more
15:43:13.705 [Thread-4] INFO org.apache.flink.yarn.YarnClusterClient - Shutting down YarnClusterClient from the client shutdown hook
15:43:13.706 [Thread-4] INFO org.apache.flink.yarn.YarnClusterClient - Disconnecting YarnClusterClient from ApplicationMaster

**Comment by zhihui-ge** [comment]
yarn模式运行的时候，有运行taskmanager的机器上都要有flinkx吗？flink的包需要使用包含hadoop的包吗？例如flink-1.4.2-bin-hadoop27-scala_2.11.tgz

**Comment by yangsishu** [comment]
flinkx 的包需要在每台taskmanager和jobmanager 的机器上都配置的

**Comment by yangsishu** [comment]
flink本生都会自带hadoop包的

**Comment by zhihui-ge** [comment]
好像是不一样的，用flink-1.4.2-bin-scala_2.11.tgz这种包启动的yarn-session，运行任务的时候会报错，找不到这个类org.apache.hadoop.mapred.FileOutputFormat，flink-1.4.2-bin-hadoop27-scala_2.11.tgz这种包启动的yarn-session，运行任务是没有问题，这也可能和我们集群的环境可能有关。
![image](https://user-images.githubusercontent.com/17016370/43235365-2d5a0c8e-90b3-11e8-81be-67fdc57353f9.png)
![image](https://user-images.githubusercontent.com/17016370/43235375-36ab72d2-90b3-11e8-9eec-0d10decb43a2.png)
