### ISSUE TITLE
standalone提交任务运行报错，local模式是好的

### ISSUE THREAD

**Issue by momisabuilder** [DTStack/flinkx#89]
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:899)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at com.dtstack.flinkx.config.DataTransferConfig.parse(DataTransferConfig.java:107)
	at com.dtstack.flinkx.launcher.Launcher.analyzeUserClasspath(Launcher.java:61)
	at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:96)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	... 6 more

**Comment by yangsishu** [comment]
配置发下

**Comment by momisabuilder** [comment]
{
    "job": {
        "setting": {
            "speed": {
                 "channel": 3,
                 "bytes": 0
            },
            "errorLimit": {
                "record": 10000,
                "percentage": 100
            }
        },
        "content": [
            {
                "reader": {
                    "name": "mysqlreader",
                    "parameter": {
                        "username": "root",
                        "password": "root",
                        "column": [
                            "id",
                            "name",
			                "age",
			                "birth"                        
                        ],
                        "where": "id > 1",
                        "connection": [
                            {
                                "table": [
                                    "student"
                                ],
                                "jdbcUrl": [
                                    "jdbc:mysql://192.168.6.184:3306/kettle?useCursorFetch=true"
                                ]
                            }
                        ],
                        "splitPk": "id",
						"conver": [
							{
								"upper": ["name"]
							}
						]
                    }
                },
               "writer": {
                    "name": "mysqlwriter",
                    "parameter": {
                        "writeMode": "insert",
                        "username": "root",
                        "password": "root",
                        "column": [
                            "target_id",
                            "target_name",
                            "target_age",
			    "target_birth"
                        ],
                        "batchSize": 1,
                        "session": [
                            "set session sql_mode='ANSI'"
                        ],
                        "connection": [
                            {
                                "jdbcUrl": "jdbc:mysql://192.168.6.184:3306/kettle?useCursorFetch=true",
                                "table": [
                                    "target_student"
                                ]
                            }
                        ]
                    }
                }
            }
        ]
    }
}

**Comment by yangsishu** [comment]
@ kanata163 看下

**Comment by yangsishu** [comment]
看下配置是不是有问题，报错就是json解析配置文件失败

**Comment by momisabuilder** [comment]
local和standalone是同一个xxx.json文件，local没问题，standalone有问题，standalone提交需要注意什么事项吗？
